[
  {"source":"HR and payroll data may contain sensitive personal and compensation information. Use role-based access, validate employee details and pay periods, and review calculations and approvals before finalizing any payroll-related workflow.","am":"የHR እና የደመወዝ ውሂብ ስሱ የግል እና የክፍያ መረጃ ሊይዝ ይችላል። በሚና ላይ የተመሰረተ መዳረሻን ይጠቀሙ፣ የሰራተኛ መረጃንና የክፍያ ጊዜዎችን ያረጋግጡ እና ማንኛውንም ከደመወዝ ጋር የተያያዘ ሂደት ከማጠናቀቅ በፊት ስሌቶችንና ማጽደቂያዎችን ይገምግሙ።"},
  {"source":"Electronic invoicing requires accurate taxpayer identity, approved submission configuration, invoice identifiers, QR or clearance evidence where applicable, offline queue handling, and cancellation records. Secret keys and certificate files must be stored only in approved secure configuration.","am":"የኤሌክትሮኒክ ደረሰኝ ትክክለኛ የግብር ከፋይ መታወቂያ፣ የተፈቀደ የማስገቢያ ውቅር፣ የደረሰኝ መለያዎች፣ ተገቢ ሲሆን የQR ወይም የማጽደቅ ማስረጃ፣ ከመስመር ውጭ የወረፋ አያያዝ እና የስረዛ መዝገቦችን ይፈልጋል። ሚስጥራዊ ቁልፎችና የምስክር ወረቀት ፋይሎች በተፈቀደ የደህንነት ውቅር ውስጥ ብቻ መቀመጥ አለባቸው።"},
  {"source":"The module catalog explains functional areas and implementation priority. Availability may depend on configuration, permissions, and rollout phase. A visible module does not automatically grant permission to view or change its records.","am":"የሞጁል ማውጫው የተግባር ክፍሎችን እና የትግበራ ቅድሚያን ያብራራል። መገኘት በውቅር፣ በፈቃዶች እና በማስጀመሪያ ደረጃ ላይ ሊመሰረት ይችላል። የሚታይ ሞጁል መዝገቦቹን ለማየት ወይም ለመቀየር ፈቃድ በራሱ አይሰጥም።"},
  {"source":"Administrators and other privileged users should enroll an authenticator and complete the required assurance step before sensitive operations. Never share passwords, one-time codes, recovery information, tokens, or secret keys.","am":"አስተዳዳሪዎች እና ሌሎች ልዩ ፈቃድ ያላቸው ተጠቃሚዎች ስሱ ስራዎችን ከመፈጸም በፊት የማረጋገጫ መተግበሪያ ማስመዝገብና የሚፈለገውን የማረጋገጫ ደረጃ ማጠናቀቅ አለባቸው። የይለፍ ቃሎችን፣ የአንድ ጊዜ ኮዶችን፣ የመመለሻ መረጃን፣ ቶከኖችን ወይም ሚስጥራዊ ቁልፎችን ፈጽሞ አያጋሩ።"},
  {"source":"Owners, administrators, accountants, sales users, inventory users, managers, staff, and viewers may have different capabilities. Use the least privilege needed for each person. Access denial usually means the user lacks the required role, organization context, or assurance level.","am":"ባለቤቶች፣ አስተዳዳሪዎች፣ የሂሳብ ሰራተኞች፣ የሽያጭ ተጠቃሚዎች፣ የክምችት ተጠቃሚዎች፣ አስተዳዳሪዎች፣ ሰራተኞች እና ተመልካቾች የተለያዩ ችሎታዎች ሊኖራቸው ይችላል። ለእያንዳንዱ ሰው አስፈላጊውን ዝቅተኛ ፈቃድ ብቻ ይስጡ። መዳረሻ መከልከል ብዙውን ጊዜ ተጠቃሚው የሚፈለገው ሚና፣ የድርጅት አውድ ወይም የማረጋገጫ ደረጃ እንደሌለው ያሳያል።"},
  {"source":"Production Controls is the operational assurance center. Review critical alerts, administrator MFA status, backup freshness, restore-test evidence, accounting integrity checks, inventory exceptions, database security checks, and deployment health before relying on the system for critical work.","am":"የምርት ቁጥጥሮች የስራ ማረጋገጫ ማዕከል ነው። ስርዓቱን ለአስፈላጊ ስራ ከመጠቀምዎ በፊት አስፈላጊ ማንቂያዎችን፣ የአስተዳዳሪ MFA ሁኔታን፣ የምትኬ ወቅታዊነትን፣ የመመለሻ ሙከራ ማስረጃን፣ የሂሳብ ታማኝነት ምርመራዎችን፣ የክምችት ልዩነቶችን፣ የዳታቤዝ ደህንነት ምርመራዎችን እና የማሰማራት ጤናን ይገምግሙ።"},
  {"source":"Use accurate user accounts, meaningful references, supporting documents, and approved workflows. Do not share accounts, edit production data directly, bypass locked periods, hide stock differences, or restore over live data without an authorized recovery plan.","am":"ትክክለኛ የተጠቃሚ መለያዎችን፣ ትርጉም ያላቸው ማጣቀሻዎችን፣ ደጋፊ ሰነዶችን እና የተፈቀዱ የስራ ሂደቶችን ይጠቀሙ። መለያዎችን አያጋሩ፣ የምርት ውሂብን በቀጥታ አያርትዑ፣ የተቆለፉ ጊዜዎችን አይዝለሉ፣ የክምችት ልዩነቶችን አይደብቁ እና የተፈቀደ የመመለሻ ዕቅድ ሳይኖር በቀጥታ ውሂብ ላይ መመለሻ አያድርጉ።"},
  {"source":"Sign in again if the session has expired. Confirm that you belong to the correct organization and have the required role. Sensitive pages may require authenticator MFA. Contact an organization owner or administrator when access is expected but still denied.","am":"ክፍለ ጊዜው ካለፈ እንደገና ይግቡ። የትክክለኛው ድርጅት አባል መሆንዎን እና የሚፈለገው ሚና እንዳለዎት ያረጋግጡ። ስሱ ገጾች የማረጋገጫ MFAን ሊፈልጉ ይችላሉ። መዳረሻ ሊኖርዎ ሲገባ ነገር ግን ከተከለከለ የድርጅቱን ባለቤት ወይም አስተዳዳሪ ያነጋግሩ።"},
  {"source":"Check the selected organization, date range, status filters, search terms, and whether the record was saved or posted successfully. Refresh the page after confirming the operation. Avoid recreating the transaction until you verify that it does not already exist.","am":"የተመረጠውን ድርጅት፣ የቀን ክልል፣ የሁኔታ ማጣሪያዎች፣ የፍለጋ ቃላት እና መዝገቡ በትክክል መቀመጡን ወይም መመዝገቡን ይመርምሩ። ስራውን ካረጋገጡ በኋላ ገጹን ያድሱ። ግብይቱ አስቀድሞ እንደሌለ እስኪያረጋግጡ ድረስ እንደገና ከመፍጠር ይቆጠቡ።"},
  {"source":"Differences often come from draft or unposted records, incorrect dates, partial payments, tax treatment, duplicate entries, period selection, or reconciliation timing. Trace the result back to source documents and balanced journal entries before making corrections.","am":"ልዩነቶች ብዙውን ጊዜ ከረቂቅ ወይም ካልተመዘገቡ መዝገቦች፣ ከተሳሳቱ ቀናት፣ ከከፊል ክፍያዎች፣ ከግብር አያያዝ፣ ከተደጋገሙ መዝገቦች፣ ከጊዜ ምርጫ ወይም ከማስታረቅ ጊዜ ይመጣሉ። እርማት ከማድረግ በፊት ውጤቱን ወደ ምንጭ ሰነዶች እና ሚዛናዊ የጆርናል መዝገቦች ይከታተሉ።"},
  {"source":"Review the product, warehouse, movement history, document dates, and posting status. Confirm whether a sale, purchase, return, transfer, or adjustment created the difference. Correct the source workflow when possible instead of adding an unexplained stock adjustment.","am":"ምርቱን፣ መጋዘኑን፣ የእንቅስቃሴ ታሪክን፣ የሰነድ ቀናትን እና የመመዝገብ ሁኔታን ይገምግሙ። ልዩነቱን ሽያጭ፣ ግዢ፣ መመለሻ፣ ዝውውር ወይም ማስተካከያ እንደፈጠረ ያረጋግጡ። ያልተብራራ የክምችት ማስተካከያ ከመጨመር ይልቅ ከተቻለ የምንጭ ሂደቱን ያስተካክሉ።"},
  {"source":"Administrators should review Production Controls and deployment health before retrying critical work. Preserve any error message, page, time, and action that triggered the problem. Do not repeatedly submit financial transactions during an uncertain outage.","am":"አስተዳዳሪዎች አስፈላጊ ስራን እንደገና ከመሞከራቸው በፊት የምርት ቁጥጥሮችን እና የማሰማራት ጤናን መገምገም አለባቸው። ችግኙን ያስነሳውን ማንኛውንም የስህተት መልዕክት፣ ገጽ፣ ጊዜ እና እርምጃ ይያዙ። ሁኔታው ያልተረጋገጠ በሆነ መቋረጥ ጊዜ የፋይናንስ ግብይቶችን በተደጋጋሚ አያስገቡ።"}
]
