import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(path)=>readFile(path,"utf8");

test("shared icon component enforces one accessible outline system",async()=>{const icon=await read("components/ui/icon.tsx");assert.match(icon,/export type IconName/);assert.match(icon,/viewBox="0 0 24 24"/);assert.match(icon,/strokeWidth="1\.8"/);assert.match(icon,/strokeLinecap="round"/);assert.match(icon,/aria-hidden=\{label \? undefined : true\}/);assert.match(icon,/aria-label=\{label\}/);assert.doesNotMatch(icon,/telebirr|M-PESA|Visa|Mastercard|Apple Pay|Google Pay/i)});

test("primary navigation, theme and account controls use shared icons",async()=>{const [shell,theme,menu]=await Promise.all([read("components/workspace-shell.tsx"),read("components/theme-toggle.tsx"),read("components/user-menu.tsx")]);for(const value of [shell,theme,menu])assert.match(value,/from "\.\/ui\/icon"/);for(const symbol of ["◉","●","◎","↪","☾","☀"])assert.equal(`${shell}${theme}${menu}`.includes(symbol),false,`legacy symbol ${symbol} must not remain`);assert.match(shell,/sidebar-nav-icon/);assert.match(shell,/icon:"home"/);assert.match(shell,/icon:"refresh-cw"/);assert.match(theme,/name=\{theme==="dark"\?"moon":"sun"\}/);assert.match(menu,/name="log-out"/)});

test("dashboard and reconciliation actions use the shared icon language",async()=>{const [dashboard,reconciliation]=await Promise.all([read("components/dashboard.tsx"),read("components/reconciliation-workspace.tsx")]);assert.match(dashboard,/import \{ Icon,type IconName \} from "\.\/ui\/icon"/);assert.doesNotMatch(dashboard,/function Icon\(/);assert.match(dashboard,/name="download"/);assert.match(dashboard,/name=\{transaction\.type==="income"\?"trending-up":"trending-down"\}/);assert.match(reconciliation,/PaymentBrandRow/);assert.match(reconciliation,/name="file-up"/);assert.match(reconciliation,/name="check-circle"/);assert.match(reconciliation,/name="rotate-ccw"/);assert.match(reconciliation,/name="alert-triangle"/)});

test("payment trademarks are never recreated as product SVG icons",async()=>{const [brands,icons,csp]=await Promise.all([read("components/payment-brand.tsx"),read("components/ui/icon.tsx"),read("proxy.ts")]);assert.match(brands,/www\.ethiotelecom\.et\/wp-content\/uploads\/2025\/10\/telebirr-logo-01\.png/);assert.match(brands,/www\.safaricom\.co\.ke\/brand-assets\?id=2021/);assert.match(brands,/Official logo upload required/);assert.doesNotMatch(brands,/<svg/);assert.doesNotMatch(icons,/PaymentBrandName/);assert.match(csp,/https:\/\/www\.ethiotelecom\.et/)});

test("global icon styles preserve sizing, focus and dark-mode brand treatment",async()=>{const [layout,styles]=await Promise.all([read("app/layout.tsx"),read("app/icon-system.css")]);assert.match(layout,/import "\.\/icon-system\.css"/);assert.match(styles,/sidebar-nav-icon\{width:20px;height:20px/);assert.match(styles,/icon-only:focus-visible/);assert.match(styles,/payment-brand-row/);assert.match(styles,/payment-brand\.primary/);assert.match(styles,/\[data-theme="dark"\] \.payment-brand/);assert.match(styles,/@keyframes hisab-icon-spin/)});
