export function getDashboardInterfaceCopy(language: string) {
  return language === "am"
    ? {
        home: "መነሻ",
        dashboard: "ዳሽቦርድ",
        overview: "የንግድ አጠቃላይ እይታ",
        financialSnapshot: "የፋይናንስ ማጠቃለያ",
        financialSnapshotDescription: "ገንዘብ፣ ሽያጭ፣ ወጪ፣ ተሰብሳቢ ሂሳብ እና የስራ ውጤት።",
        sales: "የዛሬ ሽያጭ",
        expenses: "የዛሬ ወጪ",
        cash: "ያለ ገንዘብ",
        receivables: "ተሰብሳቢ ሂሳብ",
        operatingResult: "የስራ ውጤት",
        positiveResult: "ሽያጭ ከወጪ በላይ ነው",
        negativeResult: "ወጪ ከሽያጭ በላይ ነው",
        attention: "ትኩረት የሚፈልጉ",
        attentionDescription: "ቀጣዩን ተግባር በቀጥታ የሚያሳዩ የስራ ምልክቶች።",
        collectReceivables: "የደንበኛ ተሰብሳቢ ሂሳብ",
        collectReceivablesDescription: "ያልተሰበሰበውን የደንበኛ ቀሪ ሂሳብ ይገምግሙ።",
        reviewCustomers: "ደንበኞችን ይክፈቱ",
        operatingMargin: "የሽያጭ እና ወጪ ልዩነት",
        operatingMarginDescription: "የዛሬን ሽያጭ ከወጪ ጋር ያረጋግጡ።",
        reviewFinance: "ፋይናንስን ይገምግሙ",
        reconciliation: "የባንክ እና ክፍያ ማስታረቅ",
        reconciliationDescription: "የጊዜ መዝጊያ በፊት ያልተጣጣሙ ክፍያዎችን ያረጋግጡ።",
        reconcile: "ማስታረቅን ይክፈቱ",
        businessHealth: "የንግድ ጤና",
        businessHealthDescription: "የገንዘብ ፍሰት፣ ወጪ ቁጥጥር እና ዕዳ ስብስብን ይከታተሉ።",
        openReports: "ሪፖርቶችን ይክፈቱ",
        recommendedWorkspaces: "የሚመከሩ የስራ ቦታዎች",
        recommendedWorkspacesDescription: "ለእርስዎ ሚና በጣም ጠቃሚ የሆኑ የስራ ፍሰቶች።",
        priorityModules: "ዋና የERP ሞጁሎች",
        exploreModule: "ሞጁሉን ይክፈቱ",
        performance: "የፋይናንስ አፈጻጸም",
        recentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
        recentActivityDescription: "የቅርብ ጊዜ ገቢ እና ወጪ መዝገቦች።",
        transaction: "ግብይት",
        category: "ምድብ",
        date: "ቀን",
        amount: "መጠን",
        noTransactions: "ምንም የቅርብ ጊዜ ግብይት የለም",
        noTransactionsDescription: "የተመዘገቡ ግብይቶች እዚህ ይታያሉ።",
        viewAll: "ሁሉንም ይመልከቱ",
        liveWorkspace: "ቀጥታ የስራ ቦታ",
        roleContext: "የዳሽቦርድ ቅድሚያዎች ከተመደበው ሚና ጋር ይጣጣማሉ።",
      }
    : {
        home: "Home",
        dashboard: "Dashboard",
        overview: "Business overview",
        financialSnapshot: "Financial snapshot",
        financialSnapshotDescription: "Cash, sales, expenses, receivables and operating result at a glance.",
        sales: "Sales today",
        expenses: "Expenses today",
        cash: "Cash available",
        receivables: "Receivables",
        operatingResult: "Operating result",
        positiveResult: "Sales are above expenses",
        negativeResult: "Expenses are above sales",
        attention: "Needs attention",
        attentionDescription: "Operational signals with a direct next action.",
        collectReceivables: "Customer receivables",
        collectReceivablesDescription: "Review customer balances that remain outstanding.",
        reviewCustomers: "Open customers",
        operatingMargin: "Sales and expense position",
        operatingMarginDescription: "Confirm today’s sales against operating expenses.",
        reviewFinance: "Review finance",
        reconciliation: "Bank and payment reconciliation",
        reconciliationDescription: "Review unmatched payment activity before period close.",
        reconcile: "Open reconciliation",
        businessHealth: "Business health",
        businessHealthDescription: "Track cash flow, expense control and debt collection together.",
        openReports: "Open reports",
        recommendedWorkspaces: "Recommended workspaces",
        recommendedWorkspacesDescription: "The most relevant operating flows for your assigned role.",
        priorityModules: "Priority ERP modules",
        exploreModule: "Open module",
        performance: "Financial performance",
        recentActivity: "Recent activity",
        recentActivityDescription: "The latest income and expense records across the business.",
        transaction: "Transaction",
        category: "Category",
        date: "Date",
        amount: "Amount",
        noTransactions: "No recent transactions",
        noTransactionsDescription: "Posted income and expense activity will appear here.",
        viewAll: "View all",
        liveWorkspace: "Live workspace",
        roleContext: "Dashboard priorities adapt to your assigned role.",
      };
}
