"use client";

import { useState } from "react";
import {
  approvePayrollRunAction,
  createEmployeeAction,
  createLeaveRequestAction,
  createPayrollRunAction,
  markPayrollPaidAction,
  postPayrollRunAction,
  recordAttendanceAction,
  setLeaveRequestStatusAction,
  setSalaryStructureAction,
} from "../lib/actions/hr-payroll";
import { coreOperationsCopy, operationValue } from "../lib/core-operations-copy";
import type { HrPayrollSnapshot } from "../lib/data/core-operations-types";
import { DemoNotice } from "./demo-notice";
import { useLanguage } from "./language-provider";
import { PendingActionButton } from "./pending-action-button";

type Tab = "overview" | "employees" | "attendance" | "leave" | "payroll";
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => `${today().slice(0, 8)}01`;
const monthEnd = () => new Date(Number(today().slice(0, 4)), Number(today().slice(5, 7)), 0).toISOString().slice(0, 10);
const money = (value: number) => new Intl.NumberFormat("en-ET", { style: "currency", currency: "ETB", maximumFractionDigits: 2 }).format(value || 0);
function Status({ value }: { value: string }) { const { language } = useLanguage(); return <span className={`core-status ${value.replaceAll("_", "-")}`}>{operationValue(value, language)}</span>; }
function Empty({ label }: { label: string }) { return <div className="core-empty">{label}</div>; }

export function HrPayrollWorkspace({ snapshot, initialTab, canManage }: { snapshot: HrPayrollSnapshot; initialTab?: string; canManage: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  const tabs: Array<[Tab, string]> = [["overview", c.overview], ["employees", c.employees], ["attendance", c.attendance], ["leave", c.leave], ["payroll", c.payroll]];
  const [tab, setTab] = useState<Tab>(tabs.some(([key]) => key === initialTab) ? initialTab as Tab : "overview");
  const disabled = snapshot.mode === "demo" || !canManage;
  const activeEmployees = snapshot.employees.filter((employee) => employee.status === "active");
  const withoutSalary = activeEmployees.filter((employee) => employee.baseSalary === null);
  const openLeave = snapshot.leaves.filter((leave) => leave.status === "submitted");
  const latestPayroll = snapshot.payrollRuns[0];

  return <main className="core-page">
    <header className="core-hero"><div><p className="eyebrow">Phase 2 · People operations</p><h1>Human Resources & Payroll</h1><p>Employee records, attendance, leave approvals, salary structures, configurable payroll calculation, accounting posting and payment confirmation.</p></div><div className="core-live"><span /><div><small>{c.live}</small><strong>{snapshot.organizationName}</strong></div></div></header>
    <DemoNotice mode={snapshot.mode} />{!canManage && snapshot.mode === "live" && <div className="form-alert warning">{c.readOnly}</div>}
    <div className="core-compliance-note">{c.configurableNotice}</div>
    <nav className="core-tabs" aria-label="HR and payroll sections">{tabs.map(([key, label]) => <button type="button" key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>

    {tab === "overview" && <div className="core-view"><section className="core-kpis"><article><span>{c.employees}</span><strong>{activeEmployees.length}</strong><small>{snapshot.employees.length - activeEmployees.length} inactive / leave</small></article><article className={withoutSalary.length ? "attention" : "positive"}><span>Salary setup</span><strong>{withoutSalary.length}</strong><small>Missing structures</small></article><article className={openLeave.length ? "attention" : "positive"}><span>Leave approvals</span><strong>{openLeave.length}</strong><small>Awaiting decision</small></article><article><span>Latest net payroll</span><strong>{money(latestPayroll?.netPay || 0)}</strong><small>{latestPayroll?.number || "No run"}</small></article></section><section className="core-grid three"><article className="core-panel"><h2>People by department</h2>{Array.from(new Set(snapshot.employees.map((employee) => employee.department || "Unassigned"))).map((department) => <div className="core-summary-row" key={department}><span>{department}</span><strong>{snapshot.employees.filter((employee) => (employee.department || "Unassigned") === department).length}</strong></div>)}</article><article className="core-panel"><h2>Today’s attendance</h2>{snapshot.attendance.filter((entry) => entry.date === today()).length ? snapshot.attendance.filter((entry) => entry.date === today()).slice(0, 8).map((entry) => <div className="core-summary-row" key={entry.id}><span>{entry.employeeName}</span><Status value={entry.status} /></div>) : <Empty label="No attendance recorded today" />}</article><article className="core-panel"><h2>Payroll control</h2><div className="core-summary-row"><span>Gross pay</span><strong>{money(latestPayroll?.grossPay || 0)}</strong></div><div className="core-summary-row"><span>Employee pension</span><strong>{money(latestPayroll?.employeePension || 0)}</strong></div><div className="core-summary-row"><span>Income tax</span><strong>{money(latestPayroll?.incomeTax || 0)}</strong></div><div className="core-summary-row"><span>Status</span>{latestPayroll ? <Status value={latestPayroll.status} /> : <strong>—</strong>}</div></article></section></div>}

    {tab === "employees" && <div className="core-view two"><section className="core-panel"><div className="core-panel-head"><div><p className="eyebrow">Employee master</p><h2>{c.employees}</h2></div><span>{snapshot.employees.length}</span></div>{snapshot.employees.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>{c.employee}</th><th>Department</th><th>Employment</th><th>Base salary</th><th>Rates</th><th>{c.status}</th></tr></thead><tbody>{snapshot.employees.map((employee) => <tr key={employee.id}><td><strong>{employee.fullName}</strong><small>{employee.number} · {employee.position || "—"}</small></td><td>{employee.department || "—"}</td><td>{operationValue(employee.employmentType, language)}</td><td>{employee.baseSalary === null ? <span className="core-danger">Not configured</span> : money(employee.baseSalary)}</td><td><small>Pension: {employee.employeePensionRate ?? 0}% / {employee.employerPensionRate ?? 0}%</small><small>Tax: {employee.incomeTaxRate ?? 0}%</small></td><td><Status value={employee.status} /></td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><div className="core-stack"><section className="core-panel"><p className="eyebrow">People record</p><h2>Add employee</h2><form action={createEmployeeAction} className="core-form"><label>First name<input name="firstName" required disabled={disabled} /></label><label>Last name<input name="lastName" required disabled={disabled} /></label><label>Email<input name="email" type="email" disabled={disabled} /></label><label>Phone<input name="phone" disabled={disabled} /></label><label>Tax ID<input name="taxId" disabled={disabled} /></label><label>Pension ID<input name="pensionId" disabled={disabled} /></label><label>Hire date<input name="hireDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>Employment<select name="employmentType" defaultValue="permanent" disabled={disabled}><option value="permanent">Permanent</option><option value="contract">Contract</option><option value="temporary">Temporary</option><option value="intern">Intern</option></select></label><label>Department<input name="department" disabled={disabled} /></label><label>Position<input name="positionTitle" disabled={disabled} /></label><label>Bank<input name="bankName" disabled={disabled} /></label><label>Account (masked)<input name="bankAccountMasked" placeholder="****1234" disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Saving…" disabled={disabled}>{c.save}</PendingActionButton></form></section><SalaryForm snapshot={snapshot} disabled={disabled} /></div></div>}

    {tab === "attendance" && <div className="core-view two"><section className="core-panel"><h2>{c.attendance}</h2>{snapshot.attendance.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>{c.employee}</th><th>{c.date}</th><th>{c.status}</th><th>Hours</th><th>Overtime</th></tr></thead><tbody>{snapshot.attendance.map((entry) => <tr key={entry.id}><td>{entry.employeeName}</td><td>{entry.date}</td><td><Status value={entry.status} /></td><td>{entry.regularHours}</td><td>{entry.overtimeHours}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Daily time record</p><h2>Record attendance</h2><form action={recordAttendanceAction} className="core-form"><label className="full">{c.employee}<select name="employeeId" required disabled={disabled}><option value="">Select</option>{activeEmployees.map((employee) => <option value={employee.id} key={employee.id}>{employee.number} · {employee.fullName}</option>)}</select></label><label>{c.date}<input name="attendanceDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>{c.status}<select name="status" defaultValue="present" disabled={disabled}><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="half_day">Half day</option><option value="remote">Remote</option><option value="holiday">Holiday</option><option value="leave">Leave</option></select></label><label>Check in<input name="checkIn" type="time" defaultValue="08:00" disabled={disabled} /></label><label>Check out<input name="checkOut" type="time" defaultValue="17:00" disabled={disabled} /></label><label>Regular hours<input name="regularHours" type="number" min="0" step="0.25" defaultValue="8" disabled={disabled} /></label><label>Overtime hours<input name="overtimeHours" type="number" min="0" step="0.25" defaultValue="0" disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Recording…" disabled={disabled || !activeEmployees.length}>{c.save}</PendingActionButton></form></section></div>}

    {tab === "leave" && <div className="core-view two"><section className="core-panel"><h2>{c.leave}</h2>{snapshot.leaves.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Request</th><th>{c.employee}</th><th>Type</th><th>Dates</th><th>{c.status}</th><th>{c.actions}</th></tr></thead><tbody>{snapshot.leaves.map((leave) => <tr key={leave.id}><td><strong>{leave.number}</strong><small>{leave.reason || "—"}</small></td><td>{leave.employeeName}</td><td>{operationValue(leave.type, language)}</td><td>{leave.startDate} → {leave.endDate}<small>{leave.days} days</small></td><td><Status value={leave.status} /></td><td>{leave.status === "submitted" && canManage ? <div className="core-row-actions"><form action={setLeaveRequestStatusAction}><input type="hidden" name="leaveRequestId" value={leave.id} /><input type="hidden" name="status" value="approved" /><PendingActionButton pendingLabel="…">{c.approve}</PendingActionButton></form><form action={setLeaveRequestStatusAction}><input type="hidden" name="leaveRequestId" value={leave.id} /><input type="hidden" name="status" value="rejected" /><PendingActionButton pendingLabel="…">{c.reject}</PendingActionButton></form></div> : "—"}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Employee request</p><h2>New leave request</h2><form action={createLeaveRequestAction} className="core-form"><label className="full">{c.employee}<select name="employeeId" required disabled={disabled}><option value="">Select</option>{snapshot.employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.number} · {employee.fullName}</option>)}</select></label><label>Leave type<select name="leaveType" defaultValue="annual" disabled={disabled}><option value="annual">Annual</option><option value="sick">Sick</option><option value="maternity">Maternity</option><option value="paternity">Paternity</option><option value="unpaid">Unpaid</option><option value="other">Other</option></select></label><label>Days<input name="days" type="number" min="0.5" step="0.5" defaultValue="1" required disabled={disabled} /></label><label>Start date<input name="startDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>End date<input name="endDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label className="full">Reason<textarea name="reason" rows={3} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Submitting…" disabled={disabled || !snapshot.employees.length}>{c.submit}</PendingActionButton></form></section></div>}

    {tab === "payroll" && <div className="core-view two"><section className="core-panel"><h2>{c.payroll}</h2>{snapshot.payrollRuns.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Run</th><th>Period</th><th>Gross</th><th>Net</th><th>{c.status}</th><th>{c.actions}</th></tr></thead><tbody>{snapshot.payrollRuns.map((run) => <tr key={run.id}><td><strong>{run.number}</strong><small>{run.items.length} employees · Pay {run.payDate}</small></td><td>{run.periodStart} → {run.periodEnd}</td><td>{money(run.grossPay)}</td><td>{money(run.netPay)}</td><td><Status value={run.status} /></td><td>{canManage ? <PayrollActions run={run} accounts={snapshot.cashAccounts} /> : "—"}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Configurable calculation</p><h2>Create payroll run</h2><form action={createPayrollRunAction} className="core-form"><label>Period start<input name="periodStart" type="date" defaultValue={monthStart()} required disabled={disabled} /></label><label>Period end<input name="periodEnd" type="date" defaultValue={monthEnd()} required disabled={disabled} /></label><label>Pay date<input name="payDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={3} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Calculating…" disabled={disabled || !activeEmployees.length || withoutSalary.length === activeEmployees.length}>{c.save}</PendingActionButton></form><div className="core-preview-list"><div><span>Active employees</span><strong>{activeEmployees.length}</strong></div><div><span>Ready salary structures</span><strong>{activeEmployees.length - withoutSalary.length}</strong></div><div><span>Missing salary structures</span><strong className={withoutSalary.length ? "core-danger" : ""}>{withoutSalary.length}</strong></div></div></section></div>}
  </main>;
}

function SalaryForm({ snapshot, disabled }: { snapshot: HrPayrollSnapshot; disabled: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  return <section className="core-panel"><p className="eyebrow">Compensation</p><h2>Set salary structure</h2><form action={setSalaryStructureAction} className="core-form"><label className="full">{c.employee}<select name="employeeId" required disabled={disabled}><option value="">Select</option>{snapshot.employees.filter((employee) => employee.status !== "terminated").map((employee) => <option value={employee.id} key={employee.id}>{employee.number} · {employee.fullName}</option>)}</select></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={today()} required disabled={disabled} /></label><label>Base salary<input name="baseSalary" type="number" min="0" step="0.01" required disabled={disabled} /></label><label>Allowances<input name="recurringAllowances" type="number" min="0" step="0.01" defaultValue="0" disabled={disabled} /></label><label>Deductions<input name="recurringDeductions" type="number" min="0" step="0.01" defaultValue="0" disabled={disabled} /></label><label>Employee pension %<input name="employeePensionRate" type="number" min="0" max="100" step="0.01" defaultValue="7" disabled={disabled} /></label><label>Employer pension %<input name="employerPensionRate" type="number" min="0" max="100" step="0.01" defaultValue="11" disabled={disabled} /></label><label>Income tax %<input name="incomeTaxRate" type="number" min="0" max="100" step="0.01" defaultValue="0" disabled={disabled} /></label><label>Overtime hourly rate<input name="overtimeHourlyRate" type="number" min="0" step="0.01" defaultValue="0" disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Saving…" disabled={disabled || !snapshot.employees.length}>{c.save}</PendingActionButton></form></section>;
}
function PayrollActions({ run, accounts }: { run: HrPayrollSnapshot["payrollRuns"][number]; accounts: HrPayrollSnapshot["cashAccounts"] }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  if (run.status === "draft") return <form action={approvePayrollRunAction}><input type="hidden" name="payrollRunId" value={run.id} /><PendingActionButton pendingLabel="…">{c.approve}</PendingActionButton></form>;
  if (run.status === "approved") return <form action={postPayrollRunAction}><input type="hidden" name="payrollRunId" value={run.id} /><PendingActionButton pendingLabel="…">{c.post}</PendingActionButton></form>;
  if (run.status === "posted") return <form action={markPayrollPaidAction} className="core-inline"><input type="hidden" name="payrollRunId" value={run.id} /><select name="cashAccountId" required><option value="">Account</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.label}</option>)}</select><PendingActionButton pendingLabel="…">{c.pay}</PendingActionButton></form>;
  return <span>—</span>;
}