"use client";

import { useEffect, useState } from "react";
import { createProduct } from "../lib/actions/erp";
import {
  completeStockTransferAction,
  createStockCountAction,
  createStockTransferAction,
  postInventoryAdjustmentAction,
  postStockCountAction,
  registerInventoryTrackingAction,
  submitStockCountAction,
} from "../lib/actions/inventory-operations";
import { coreOperationsCopy, operationValue } from "../lib/core-operations-copy";
import type { InventoryOperationsSnapshot } from "../lib/data/core-operations-types";
import { DemoNotice } from "./demo-notice";
import { useLanguage } from "./language-provider";
import { PendingActionButton } from "./pending-action-button";

type Tab = "overview" | "products" | "transfers" | "counts" | "adjustments" | "tracking";
type TransferLine = { productId: string; quantity: string };
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: number) => new Intl.NumberFormat("en-ET", { style: "currency", currency: "ETB", maximumFractionDigits: 2 }).format(value || 0);

function Status({ value }: { value: string }) { const { language } = useLanguage(); return <span className={`core-status ${value.replaceAll("_", "-")}`}>{operationValue(value, language)}</span>; }
function Empty({ label }: { label: string }) { return <div className="core-empty">{label}</div>; }

function TransferLineBuilder({ snapshot }: { snapshot: InventoryOperationsSnapshot }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  const [lines, setLines] = useState<TransferLine[]>([{ productId: snapshot.products[0]?.id || "", quantity: "1" }]);
  const payload = lines.map((line) => ({ productId: line.productId, quantity: Number(line.quantity) }));
  return <div className="core-lines"><input type="hidden" name="linesJson" value={JSON.stringify(payload)} />{lines.map((line, index) => <div className="core-line compact" key={index}><select value={line.productId} onChange={(event) => setLines((current) => current.map((entry, lineIndex) => lineIndex === index ? { ...entry, productId: event.target.value } : entry))}>{snapshot.products.map((product) => <option value={product.id} key={product.id}>{product.sku} · {product.name} · {product.totalQuantity}</option>)}</select><input value={line.quantity} type="number" min="0.001" step="0.001" aria-label={c.quantity} onChange={(event) => setLines((current) => current.map((entry, lineIndex) => lineIndex === index ? { ...entry, quantity: event.target.value } : entry))} /><button type="button" className="core-remove" onClick={() => setLines((current) => current.length === 1 ? current : current.filter((_, lineIndex) => lineIndex !== index))}>×</button></div>)}<button type="button" className="core-add-line" onClick={() => setLines((current) => [...current, { productId: snapshot.products[0]?.id || "", quantity: "1" }])}>+ {c.addLine}</button></div>;
}

export function InventoryOperationsWorkspace({ snapshot, initialTab, canManage }: { snapshot: InventoryOperationsSnapshot; initialTab?: string; canManage: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  const tabs: Array<[Tab, string]> = [["overview", c.overview], ["products", c.products], ["transfers", c.transfers], ["counts", c.counts], ["adjustments", c.adjustments], ["tracking", c.tracking]];
  const [tab, setTab] = useState<Tab>(tabs.some(([key]) => key === initialTab) ? initialTab as Tab : "overview");
  const disabled = snapshot.mode === "demo" || !canManage;
  const stockValue = snapshot.products.reduce((sum, product) => sum + product.totalQuantity * product.costPrice, 0);
  const lowStock = snapshot.products.filter((product) => product.needsReorder);
  const openTransfers = snapshot.transfers.filter((transfer) => ["approved", "in_transit"].includes(transfer.status));
  const openCounts = snapshot.counts.filter((count) => ["draft", "in_progress", "submitted"].includes(count.status));
  const expiringLots = snapshot.lots.filter((lot) => lot.expiryDate && lot.expiryDate <= new Date(Date.now() + 30 * 86_400_000).toISOString().slice(0, 10) && lot.status === "active");

  return <main className="core-page">
    <header className="core-hero"><div><p className="eyebrow">Phase 1 · Inventory control</p><h1>Inventory & Warehouse</h1><p>Real-time stock by warehouse, controlled transfers, physical counts, financial adjustments, reorder signals, batches, expiry and serial-number tracking.</p></div><div className="core-live"><span /><div><small>{c.live}</small><strong>{snapshot.organizationName}</strong></div></div></header>
    <DemoNotice mode={snapshot.mode} />{!canManage && snapshot.mode === "live" && <div className="form-alert warning">{c.readOnly}</div>}
    <nav className="core-tabs" aria-label="Inventory sections">{tabs.map(([key, label]) => <button type="button" key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>

    {tab === "overview" && <div className="core-view"><section className="core-kpis"><article><span>{c.products}</span><strong>{snapshot.products.length}</strong><small>{snapshot.warehouses.length} warehouses</small></article><article className={lowStock.length ? "attention" : "positive"}><span>Reorder alerts</span><strong>{lowStock.length}</strong><small>At or below minimum</small></article><article><span>Stock value</span><strong>{money(stockValue)}</strong><small>At current cost</small></article><article className={expiringLots.length ? "attention" : "positive"}><span>Expiring lots</span><strong>{expiringLots.length}</strong><small>Within 30 days</small></article></section><section className="core-grid three"><article className="core-panel"><h2>Warehouse position</h2>{snapshot.warehouses.map((warehouse) => <div className="core-summary-row" key={warehouse.id}><span>{warehouse.label}</span><strong>{snapshot.products.reduce((sum, product) => sum + (product.balances.find((balance) => balance.warehouseId === warehouse.id)?.quantity || 0), 0).toLocaleString()}</strong></div>)}</article><article className="core-panel"><h2>Low stock</h2>{lowStock.length ? lowStock.slice(0, 8).map((product) => <div className="core-summary-row" key={product.id}><span>{product.name}<small>{product.sku}</small></span><strong className="core-danger">{product.totalQuantity}</strong></div>) : <Empty label="Stock levels are healthy" />}</article><article className="core-panel"><h2>Control queue</h2><div className="core-summary-row"><span>Open transfers</span><strong>{openTransfers.length}</strong></div><div className="core-summary-row"><span>Open counts</span><strong>{openCounts.length}</strong></div><div className="core-summary-row"><span>Adjustments posted</span><strong>{snapshot.adjustments.length}</strong></div><div className="core-summary-row"><span>Tracked serials</span><strong>{snapshot.serials.length}</strong></div></article></section></div>}

    {tab === "products" && <div className="core-view two"><section className="core-panel"><div className="core-panel-head"><div><p className="eyebrow">Live stock</p><h2>{c.products}</h2></div><span>{snapshot.products.length}</span></div>{snapshot.products.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>{c.product}</th><th>{c.warehouse}</th><th>{c.quantity}</th><th>Reorder</th><th>Value</th></tr></thead><tbody>{snapshot.products.map((product) => <tr key={product.id}><td><strong>{product.name}</strong><small>{product.sku}</small></td><td>{product.balances.map((balance) => <small key={balance.warehouseId}>{balance.warehouseName}: {balance.quantity}</small>)}</td><td className={product.needsReorder ? "core-danger" : ""}>{product.totalQuantity}</td><td>{product.reorderLevel}</td><td>{money(product.totalQuantity * product.costPrice)}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Product master</p><h2>Add product and opening stock</h2><form action={createProduct} className="core-form"><label>{c.warehouse}<select name="warehouseId" required disabled={disabled}><option value="">Select</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select></label><label>SKU<input name="sku" required disabled={disabled} /></label><label className="full">Name<input name="name" required disabled={disabled} /></label><label>Unit price<input name="unitPrice" type="number" min="0" step="0.01" defaultValue="0" required disabled={disabled} /></label><label>Cost price<input name="costPrice" type="number" min="0" step="0.01" defaultValue="0" disabled={disabled} /></label><label>Opening quantity<input name="openingQuantity" type="number" min="0" step="0.001" defaultValue="0" disabled={disabled} /></label><label>Reorder level<input name="reorderLevel" type="number" min="0" step="0.001" defaultValue="0" disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Saving…" disabled={disabled || !snapshot.warehouses.length}>{c.save}</PendingActionButton></form></section></div>}

    {tab === "transfers" && <div className="core-view two"><section className="core-panel"><h2>{c.transfers}</h2>{snapshot.transfers.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Transfer</th><th>Route</th><th>{c.date}</th><th>Items</th><th>{c.status}</th><th>{c.actions}</th></tr></thead><tbody>{snapshot.transfers.map((transfer) => <tr key={transfer.id}><td><strong>{transfer.number}</strong><small>{transfer.notes || "—"}</small></td><td>{transfer.sourceWarehouse} → {transfer.destinationWarehouse}</td><td>{transfer.date}</td><td>{transfer.items.length}</td><td><Status value={transfer.status} /></td><td>{["approved", "in_transit"].includes(transfer.status) && canManage ? <form action={completeStockTransferAction}><input type="hidden" name="stockTransferId" value={transfer.id} /><PendingActionButton pendingLabel="…">{c.complete}</PendingActionButton></form> : "—"}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Inter-warehouse</p><h2>New stock transfer</h2><form action={createStockTransferAction} className="core-form"><label>From<select name="sourceWarehouseId" required disabled={disabled}><option value="">Select</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select></label><label>To<select name="destinationWarehouseId" required disabled={disabled}><option value="">Select</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select></label><label>{c.date}<input name="transferDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><div className="full"><TransferLineBuilder snapshot={snapshot} /></div><PendingActionButton className="primary full" pendingLabel="Creating…" disabled={disabled || snapshot.warehouses.length < 2 || !snapshot.products.length}>{c.save}</PendingActionButton></form></section></div>}

    {tab === "counts" && <div className="core-view two"><section className="core-panel"><h2>{c.counts}</h2>{snapshot.counts.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Count</th><th>{c.warehouse}</th><th>{c.date}</th><th>Variance</th><th>{c.status}</th><th>{c.actions}</th></tr></thead><tbody>{snapshot.counts.map((count) => <tr key={count.id}><td><strong>{count.number}</strong><small>{count.notes || "—"}</small></td><td>{count.warehouseName}</td><td>{count.date}</td><td>{count.items.reduce((sum, item) => sum + item.variance, 0)}</td><td><Status value={count.status} /></td><td>{canManage && count.status === "submitted" ? <form action={postStockCountAction}><input type="hidden" name="stockCountId" value={count.id} /><PendingActionButton pendingLabel="…">{c.post}</PendingActionButton></form> : "—"}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><div className="core-stack"><section className="core-panel"><p className="eyebrow">Physical control</p><h2>Start stock count</h2><form action={createStockCountAction} className="core-form"><label>{c.warehouse}<select name="warehouseId" required disabled={disabled}><option value="">Select</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select></label><label>{c.date}<input name="countDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Starting…" disabled={disabled || !snapshot.warehouses.length}>{c.save}</PendingActionButton></form></section><CountSubmission counts={snapshot.counts.filter((count) => ["draft", "in_progress"].includes(count.status))} disabled={disabled} /></div></div>}

    {tab === "adjustments" && <div className="core-view two"><section className="core-panel"><h2>{c.adjustments}</h2>{snapshot.adjustments.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Adjustment</th><th>{c.product}</th><th>{c.warehouse}</th><th>Type</th><th>{c.quantity}</th><th>Value</th></tr></thead><tbody>{snapshot.adjustments.map((adjustment) => <tr key={adjustment.id}><td><strong>{adjustment.number}</strong><small>{adjustment.date}</small></td><td>{adjustment.productName}</td><td>{adjustment.warehouseName}</td><td><Status value={adjustment.type} /></td><td>{adjustment.quantity}</td><td>{money(adjustment.value)}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Controlled correction</p><h2>Post adjustment</h2><form action={postInventoryAdjustmentAction} className="core-form"><label>{c.product}<select name="productId" required disabled={disabled}><option value="">Select</option>{snapshot.products.map((product) => <option value={product.id} key={product.id}>{product.sku} · {product.name}</option>)}</select></label><label>{c.warehouse}<select name="warehouseId" required disabled={disabled}><option value="">Select</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select></label><label>Type<select name="adjustmentType" defaultValue="increase" disabled={disabled}><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label><label>{c.quantity}<input name="quantity" type="number" min="0.001" step="0.001" required disabled={disabled} /></label><label>{c.date}<input name="adjustmentDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label className="full">Reason<textarea name="reason" rows={3} required disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Posting…" disabled={disabled || !snapshot.products.length || !snapshot.warehouses.length}>{c.post}</PendingActionButton></form></section></div>}

    {tab === "tracking" && <div className="core-view two"><section className="core-panel"><h2>{c.tracking}</h2><div className="core-split-list"><div><h3>Lots</h3>{snapshot.lots.length ? snapshot.lots.map((lot) => <div className="core-summary-row" key={lot.id}><span>{lot.lotNumber}<small>{lot.productName} · {lot.warehouseName}</small></span><strong>{lot.quantity} · {lot.expiryDate || "No expiry"}</strong></div>) : <Empty label={c.noRecords} />}</div><div><h3>Serials</h3>{snapshot.serials.length ? snapshot.serials.slice(0, 100).map((serial) => <div className="core-summary-row" key={serial.id}><span>{serial.serialNumber}<small>{serial.productName}</small></span><Status value={serial.status} /></div>) : <Empty label={c.noRecords} />}</div></div></section><section className="core-panel"><p className="eyebrow">Traceability</p><h2>Register lot and serials</h2><form action={registerInventoryTrackingAction} className="core-form"><label>{c.product}<select name="productId" required disabled={disabled}><option value="">Select</option>{snapshot.products.map((product) => <option value={product.id} key={product.id}>{product.sku} · {product.name}</option>)}</select></label><label>{c.warehouse}<select name="warehouseId" required disabled={disabled}><option value="">Select</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select></label><label>Lot number<input name="lotNumber" disabled={disabled} /></label><label>{c.quantity}<input name="quantity" type="number" min="0" step="0.001" defaultValue="0" disabled={disabled} /></label><label>Manufactured<input name="manufactureDate" type="date" disabled={disabled} /></label><label>Expires<input name="expiryDate" type="date" disabled={disabled} /></label><label className="full">Serial numbers<textarea name="serialNumbers" rows={7} placeholder="One per line or comma-separated" disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Registering…" disabled={disabled || !snapshot.products.length || !snapshot.warehouses.length}>{c.save}</PendingActionButton></form></section></div>}
  </main>;
}

function CountSubmission({ counts, disabled }: { counts: InventoryOperationsSnapshot["counts"]; disabled: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language]; const [countId, setCountId] = useState(counts[0]?.id || ""); const count = counts.find((entry) => entry.id === countId); const [values, setValues] = useState<Record<string, string>>({});
  useEffect(() => { if (count) setValues(Object.fromEntries(count.items.map((item) => [item.id, String(item.countedQuantity ?? item.systemQuantity)]))); }, [count]);
  const payload = count?.items.map((item) => ({ stockCountItemId: item.id, countedQuantity: Number(values[item.id] ?? item.systemQuantity) })) || [];
  return <section className="core-panel"><p className="eyebrow">Count sheet</p><h2>{c.submit}</h2><form action={submitStockCountAction} className="core-form"><label className="full">Open count<select name="stockCountId" value={countId} onChange={(event) => setCountId(event.target.value)} required disabled={disabled}><option value="">Select</option>{counts.map((entry) => <option value={entry.id} key={entry.id}>{entry.number} · {entry.warehouseName}</option>)}</select></label><input type="hidden" name="linesJson" value={JSON.stringify(payload)} /><div className="full core-count-sheet">{count?.items.map((item) => <label key={item.id}><span>{item.productName}<small>System: {item.systemQuantity}</small></span><input type="number" min="0" step="0.001" value={values[item.id] ?? ""} onChange={(event) => setValues((current) => ({ ...current, [item.id]: event.target.value }))} disabled={disabled} /></label>)}</div><PendingActionButton className="primary full" pendingLabel="Submitting…" disabled={disabled || !payload.length}>{c.submit}</PendingActionButton></form></section>;
}