"use client";

import { useMemo, useState } from "react";
import {
  convertSupplierQuoteAction,
  createPurchaseRequestAction,
  createSupplierAction,
  createSupplierQuoteAction,
  postPurchaseReturnAction,
  postSupplierBillAction,
  recordGoodsReceiptAction,
  recordSupplierPaymentAction,
  setPurchaseRequestStatusAction,
} from "../lib/actions/purchasing";
import { coreOperationsCopy, operationValue } from "../lib/core-operations-copy";
import type { PurchasingSnapshot } from "../lib/data/core-operations-types";
import { DemoNotice } from "./demo-notice";
import { useLanguage } from "./language-provider";
import { PendingActionButton } from "./pending-action-button";

type Tab = "overview" | "suppliers" | "requests" | "quotes" | "orders" | "receipts" | "bills" | "returns";
type Line = { productId: string; warehouseId: string; description: string; quantity: string; unitCost: string; taxRate: string };
const blankLine = (): Line => ({ productId: "", warehouseId: "", description: "", quantity: "1", unitCost: "0", taxRate: "15" });
const money = (value: number) => new Intl.NumberFormat("en-ET", { style: "currency", currency: "ETB", maximumFractionDigits: 2 }).format(value || 0);
const today = () => new Date().toISOString().slice(0, 10);
const plusDays = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);

function Status({ value }: { value: string }) {
  const { language } = useLanguage();
  return <span className={`core-status ${value.replaceAll("_", "-")}`}>{operationValue(value, language)}</span>;
}
function Empty({ label }: { label: string }) { return <div className="core-empty">{label}</div>; }

function LineBuilder({ snapshot, kind }: { snapshot: PurchasingSnapshot; kind: "request" | "quote" }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  const [lines, setLines] = useState<Line[]>([blankLine()]);
  const update = (index: number, key: keyof Line, value: string) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, [key]: value } : line));
  const payload = lines.map((line) => kind === "request" ? { productId: line.productId || null, warehouseId: line.warehouseId || null, description: line.description, quantity: Number(line.quantity), estimatedUnitCost: Number(line.unitCost) } : { productId: line.productId || null, warehouseId: line.warehouseId || null, description: line.description, quantity: Number(line.quantity), unitCost: Number(line.unitCost), taxRate: Number(line.taxRate) });
  return <div className="core-lines"><input type="hidden" name="linesJson" value={JSON.stringify(payload)} />{lines.map((line, index) => <div className="core-line" key={index}>
    <select value={line.productId} onChange={(event) => update(index, "productId", event.target.value)}><option value="">Custom item</option>{snapshot.products.map((product) => <option value={product.id} key={product.id}>{product.sku} · {product.name}</option>)}</select>
    <select value={line.warehouseId} onChange={(event) => update(index, "warehouseId", event.target.value)}><option value="">{c.warehouse}</option>{snapshot.warehouses.map((warehouse) => <option value={warehouse.id} key={warehouse.id}>{warehouse.label}</option>)}</select>
    <input value={line.description} onChange={(event) => update(index, "description", event.target.value)} placeholder={c.description} required={!line.productId} />
    <input value={line.quantity} onChange={(event) => update(index, "quantity", event.target.value)} type="number" min="0.001" step="0.001" aria-label={c.quantity} />
    <input value={line.unitCost} onChange={(event) => update(index, "unitCost", event.target.value)} type="number" min="0" step="0.01" aria-label={c.amount} />
    {kind === "quote" && <input value={line.taxRate} onChange={(event) => update(index, "taxRate", event.target.value)} type="number" min="0" max="100" step="0.01" aria-label="Tax rate" />}
    <button type="button" className="core-remove" onClick={() => setLines((current) => current.length === 1 ? current : current.filter((_, lineIndex) => lineIndex !== index))}>×</button>
  </div>)}<button type="button" className="core-add-line" onClick={() => setLines((current) => [...current, blankLine()])}>+ {c.addLine}</button></div>;
}

export function PurchasingWorkspace({ snapshot, initialTab, canManage }: { snapshot: PurchasingSnapshot; initialTab?: string; canManage: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language];
  const tabs: Array<[Tab, string]> = [["overview", c.overview], ["suppliers", c.suppliers], ["requests", c.requests], ["quotes", c.quotes], ["orders", c.orders], ["receipts", c.receipts], ["bills", c.bills], ["returns", c.returns]];
  const [tab, setTab] = useState<Tab>(tabs.some(([key]) => key === initialTab) ? initialTab as Tab : "overview");
  const disabled = snapshot.mode === "demo" || !canManage;
  const openBills = snapshot.bills.filter((bill) => bill.outstanding > 0 && ["posted", "partially_paid"].includes(bill.status));
  const approvedRequests = snapshot.requests.filter((request) => request.status === "approved");
  const activeQuotes = snapshot.quotes.filter((quote) => ["received", "selected"].includes(quote.status));
  const receivableOrders = snapshot.orders.filter((order) => ["approved", "sent", "partially_received"].includes(order.status));
  const billableOrders = snapshot.orders.filter((order) => order.items.some((item) => item.receivedQuantity > item.billedQuantity));
  const returnableOrders = snapshot.orders.filter((order) => order.items.some((item) => item.receivedQuantity > item.returnedQuantity));
  const totalPayables = snapshot.bills.reduce((sum, bill) => sum + bill.outstanding, 0);
  const overdue = snapshot.bills.filter((bill) => bill.outstanding > 0 && bill.dueDate < today()).length;

  return <main className="core-page">
    <header className="core-hero"><div><p className="eyebrow">Phase 1 · Procure-to-pay</p><h1>Purchasing & Accounts Payable</h1><p>Supplier onboarding, purchase approvals, competitive quotes, orders, receiving, bills, payments and returns in one controlled workflow.</p></div><div className="core-live"><span /><div><small>{c.live}</small><strong>{snapshot.organizationName}</strong></div></div></header>
    <DemoNotice mode={snapshot.mode} />{!canManage && snapshot.mode === "live" && <div className="form-alert warning">{c.readOnly}</div>}
    <nav className="core-tabs" aria-label="Purchasing sections">{tabs.map(([key, label]) => <button type="button" key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>

    {tab === "overview" && <div className="core-view"><section className="core-kpis"><article><span>{c.suppliers}</span><strong>{snapshot.suppliers.length}</strong><small>{snapshot.suppliers.filter((supplier) => supplier.balance > 0).length} with balance</small></article><article><span>{c.orders}</span><strong>{snapshot.orders.length}</strong><small>{receivableOrders.length} awaiting receipt</small></article><article className={overdue ? "attention" : "positive"}><span>{c.bills}</span><strong>{money(totalPayables)}</strong><small>{overdue} overdue</small></article><article><span>{c.receipts}</span><strong>{snapshot.receipts.length}</strong><small>{snapshot.returns.length} returns</small></article></section><section className="core-grid three"><article className="core-panel"><h2>Procure-to-pay flow</h2><div className="core-flow"><button onClick={() => setTab("requests")}>1. Request</button><b>→</b><button onClick={() => setTab("quotes")}>2. Quote</button><b>→</b><button onClick={() => setTab("orders")}>3. Order</button><b>→</b><button onClick={() => setTab("receipts")}>4. Receive</button><b>→</b><button onClick={() => setTab("bills")}>5. Pay</button></div></article><article className="core-panel"><h2>Open commitments</h2>{snapshot.orders.slice(0, 5).map((order) => <div className="core-summary-row" key={order.id}><span>{order.number}<small>{order.supplierName}</small></span><strong>{money(order.total)}</strong></div>)}</article><article className="core-panel"><h2>Supplier exposure</h2>{snapshot.suppliers.filter((supplier) => supplier.balance > 0).slice(0, 5).map((supplier) => <div className="core-summary-row" key={supplier.id}><span>{supplier.name}<small>{supplier.paymentTermsDays} days</small></span><strong>{money(supplier.balance)}</strong></div>)}</article></section></div>}

    {tab === "suppliers" && <div className="core-view two"><section className="core-panel"><div className="core-panel-head"><div><p className="eyebrow">Supplier master</p><h2>{snapshot.suppliers.length} suppliers</h2></div></div>{snapshot.suppliers.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>{c.supplier}</th><th>TIN</th><th>Terms</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{snapshot.suppliers.map((supplier) => <tr key={supplier.id}><td><strong>{supplier.name}</strong><small>{supplier.phone || "—"}</small></td><td>{supplier.tin || "—"}</td><td>{supplier.paymentTermsDays} days</td><td>{money(supplier.creditLimit)}</td><td className={supplier.balance > 0 ? "core-danger" : ""}>{money(supplier.balance)}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">{c.newRecord}</p><h2>Add supplier</h2><form action={createSupplierAction} className="core-form"><label className="full">Name<input name="name" required disabled={disabled} /></label><label>Email<input name="email" type="email" disabled={disabled} /></label><label>Phone<input name="phone" disabled={disabled} /></label><label>TIN<input name="tin" disabled={disabled} /></label><label>Payment terms<input name="paymentTermsDays" type="number" min="0" defaultValue="30" disabled={disabled} /></label><label>Credit limit<input name="creditLimit" type="number" min="0" step="0.01" defaultValue="0" disabled={disabled} /></label><label className="full">Bank details<textarea name="bankDetails" rows={3} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Saving…" disabled={disabled}>{c.save}</PendingActionButton></form></section></div>}

    {tab === "requests" && <div className="core-view two"><section className="core-panel"><div className="core-panel-head"><div><p className="eyebrow">Approval queue</p><h2>{c.requests}</h2></div><span>{snapshot.requests.length}</span></div>{snapshot.requests.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Request</th><th>Need by</th><th>Items</th><th>{c.status}</th><th>{c.actions}</th></tr></thead><tbody>{snapshot.requests.map((request) => <tr key={request.id}><td><strong>{request.number}</strong><small>{request.department || request.requester || "—"}</small></td><td>{request.neededBy || "—"}</td><td>{request.items.length}</td><td><Status value={request.status} /></td><td>{request.status === "submitted" && canManage ? <div className="core-row-actions"><form action={setPurchaseRequestStatusAction}><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="status" value="approved" /><PendingActionButton pendingLabel="…">{c.approve}</PendingActionButton></form><form action={setPurchaseRequestStatusAction}><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="status" value="rejected" /><PendingActionButton pendingLabel="…">{c.reject}</PendingActionButton></form></div> : "—"}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Internal demand</p><h2>New purchase request</h2><form action={createPurchaseRequestAction} className="core-form"><label>{c.date}<input name="requestDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>Needed by<input name="neededBy" type="date" defaultValue={plusDays(7)} disabled={disabled} /></label><label>Department<input name="department" disabled={disabled} /></label><label>Requested by<input name="requestedByName" disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><div className="full"><LineBuilder snapshot={snapshot} kind="request" /></div><PendingActionButton className="primary full" pendingLabel="Submitting…" disabled={disabled}>{c.submit}</PendingActionButton></form></section></div>}

    {tab === "quotes" && <div className="core-view two"><section className="core-panel"><div className="core-panel-head"><div><p className="eyebrow">Supplier comparison</p><h2>{c.quotes}</h2></div><span>{snapshot.quotes.length}</span></div>{snapshot.quotes.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Quote</th><th>{c.supplier}</th><th>{c.total}</th><th>{c.status}</th><th>{c.actions}</th></tr></thead><tbody>{snapshot.quotes.map((quote) => <tr key={quote.id}><td><strong>{quote.number}</strong><small>{quote.reference || quote.date}</small></td><td>{quote.supplierName}</td><td>{money(quote.total)}</td><td><Status value={quote.status} /></td><td>{["received", "selected"].includes(quote.status) && canManage ? <form action={convertSupplierQuoteAction} className="core-inline"><input type="hidden" name="supplierQuoteId" value={quote.id} /><input name="orderDate" type="date" defaultValue={today()} required /><input name="expectedDate" type="date" defaultValue={plusDays(7)} /><PendingActionButton pendingLabel="…">{c.convert}</PendingActionButton></form> : "—"}</td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><section className="core-panel"><p className="eyebrow">Approved demand</p><h2>Record supplier quote</h2><form action={createSupplierQuoteAction} className="core-form"><label>Purchase request<select name="purchaseRequestId" required disabled={disabled}><option value="">Select</option>{approvedRequests.map((request) => <option value={request.id} key={request.id}>{request.number}</option>)}</select></label><label>{c.supplier}<select name="supplierId" required disabled={disabled}><option value="">Select</option>{snapshot.suppliers.map((supplier) => <option value={supplier.id} key={supplier.id}>{supplier.name}</option>)}</select></label><label>{c.reference}<input name="supplierReference" disabled={disabled} /></label><label>{c.date}<input name="quoteDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>Valid until<input name="validUntil" type="date" defaultValue={plusDays(14)} disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><div className="full"><LineBuilder snapshot={snapshot} kind="quote" /></div><PendingActionButton className="primary full" pendingLabel="Saving…" disabled={disabled || !approvedRequests.length || !snapshot.suppliers.length}>{c.save}</PendingActionButton></form></section></div>}

    {tab === "orders" && <section className="core-panel"><div className="core-panel-head"><div><p className="eyebrow">Approved commitments</p><h2>{c.orders}</h2></div><span>{snapshot.orders.length}</span></div>{snapshot.orders.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Order</th><th>{c.supplier}</th><th>{c.date}</th><th>Progress</th><th>{c.total}</th><th>{c.status}</th></tr></thead><tbody>{snapshot.orders.map((order) => { const ordered = order.items.reduce((sum, item) => sum + item.quantity, 0); const received = order.items.reduce((sum, item) => sum + item.receivedQuantity, 0); return <tr key={order.id}><td><strong>{order.number}</strong><small>{order.expectedDate || "No expected date"}</small></td><td>{order.supplierName}</td><td>{order.date}</td><td>{received.toLocaleString()} / {ordered.toLocaleString()}</td><td>{money(order.total)}</td><td><Status value={order.status} /></td></tr>; })}</tbody></table></div> : <Empty label={c.noRecords} />}</section>}

    {tab === "receipts" && <div className="core-view two"><section className="core-panel"><h2>{c.receipts}</h2>{snapshot.receipts.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>GRN</th><th>Order</th><th>{c.date}</th><th>{c.reference}</th><th>{c.status}</th></tr></thead><tbody>{snapshot.receipts.map((receipt) => <tr key={receipt.id}><td><strong>{receipt.number}</strong></td><td>{snapshot.orders.find((order) => order.id === receipt.orderId)?.number || "—"}</td><td>{receipt.date}</td><td>{receipt.reference || "—"}</td><td><Status value={receipt.status} /></td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><ReceiptForm snapshot={snapshot} orders={receivableOrders} disabled={disabled} /></div>}

    {tab === "bills" && <div className="core-view two"><section className="core-panel"><h2>{c.bills}</h2>{snapshot.bills.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Bill</th><th>{c.supplier}</th><th>{c.due}</th><th>{c.total}</th><th>Outstanding</th><th>{c.status}</th></tr></thead><tbody>{snapshot.bills.map((bill) => <tr key={bill.id}><td><strong>{bill.number}</strong><small>{bill.supplierInvoiceNumber || bill.date}</small></td><td>{bill.supplierName}</td><td>{bill.dueDate}</td><td>{money(bill.total)}</td><td className={bill.outstanding > 0 ? "core-danger" : ""}>{money(bill.outstanding)}</td><td><Status value={bill.status} /></td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><div className="core-stack"><BillForm snapshot={snapshot} orders={billableOrders} disabled={disabled} /><section className="core-panel"><p className="eyebrow">Settlement</p><h2>{c.pay}</h2><form action={recordSupplierPaymentAction} className="core-form"><label className="full">Open bill<select name="supplierBillId" required disabled={disabled}><option value="">Select</option>{openBills.map((bill) => <option value={bill.id} key={bill.id}>{bill.number} · {bill.supplierName} · {money(bill.outstanding)}</option>)}</select></label><label>{c.amount}<input name="amount" type="number" min="0.01" step="0.01" required disabled={disabled} /></label><label>Method<select name="method" defaultValue="bank" disabled={disabled}><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_money">Mobile money</option></select></label><label>{c.date}<input name="paymentDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>{c.reference}<input name="reference" disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Recording…" disabled={disabled || !openBills.length}>{c.pay}</PendingActionButton></form></section></div></div>}

    {tab === "returns" && <div className="core-view two"><section className="core-panel"><h2>{c.returns}</h2>{snapshot.returns.length ? <div className="core-table-wrap"><table className="core-table"><thead><tr><th>Return</th><th>{c.supplier}</th><th>{c.date}</th><th>{c.total}</th><th>{c.status}</th></tr></thead><tbody>{snapshot.returns.map((item) => <tr key={item.id}><td><strong>{item.number}</strong><small>{item.reason || "—"}</small></td><td>{item.supplierName}</td><td>{item.date}</td><td>{money(item.total)}</td><td><Status value={item.status} /></td></tr>)}</tbody></table></div> : <Empty label={c.noRecords} />}</section><ReturnForm snapshot={snapshot} orders={returnableOrders} disabled={disabled} /></div>}
  </main>;
}

function ReceiptForm({ snapshot, orders, disabled }: { snapshot: PurchasingSnapshot; orders: PurchasingSnapshot["orders"]; disabled: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language]; const [orderId, setOrderId] = useState(orders[0]?.id || ""); const order = orders.find((item) => item.id === orderId); const payload = order?.items.filter((item) => item.quantity > item.receivedQuantity).map((item) => ({ purchaseOrderItemId: item.id, warehouseId: item.warehouseId, quantity: item.quantity - item.receivedQuantity })) || [];
  return <section className="core-panel"><p className="eyebrow">Warehouse receiving</p><h2>Post goods receipt</h2><form action={recordGoodsReceiptAction} className="core-form"><label className="full">Purchase order<select name="purchaseOrderId" value={orderId} onChange={(event) => setOrderId(event.target.value)} required disabled={disabled}><option value="">Select</option>{orders.map((item) => <option value={item.id} key={item.id}>{item.number} · {item.supplierName}</option>)}</select></label><label>{c.date}<input name="receiptDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>{c.reference}<input name="supplierDeliveryReference" disabled={disabled} /></label><input type="hidden" name="linesJson" value={JSON.stringify(payload)} /><div className="full core-preview-list">{order?.items.filter((item) => item.quantity > item.receivedQuantity).map((item) => <div key={item.id}><span>{item.description}</span><strong>{item.quantity - item.receivedQuantity}</strong></div>)}</div><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Receiving…" disabled={disabled || !payload.length}>{c.post}</PendingActionButton></form></section>;
}
function BillForm({ snapshot, orders, disabled }: { snapshot: PurchasingSnapshot; orders: PurchasingSnapshot["orders"]; disabled: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language]; const [orderId, setOrderId] = useState(orders[0]?.id || ""); const order = orders.find((item) => item.id === orderId); const receipt = snapshot.receipts.find((item) => item.orderId === orderId); const payload = order?.items.filter((item) => item.receivedQuantity > item.billedQuantity).map((item) => ({ purchaseOrderItemId: item.id, quantity: item.receivedQuantity - item.billedQuantity, unitCost: item.unitCost, taxRate: item.taxRate })) || [];
  return <section className="core-panel"><p className="eyebrow">Three-way match</p><h2>Post supplier bill</h2><form action={postSupplierBillAction} className="core-form"><label className="full">Purchase order<select name="purchaseOrderId" value={orderId} onChange={(event) => setOrderId(event.target.value)} required disabled={disabled}><option value="">Select</option>{orders.map((item) => <option value={item.id} key={item.id}>{item.number} · {item.supplierName}</option>)}</select></label><input type="hidden" name="goodsReceiptId" value={receipt?.id || ""} /><input type="hidden" name="linesJson" value={JSON.stringify(payload)} /><label>Supplier invoice<input name="supplierInvoiceNumber" disabled={disabled} /></label><label>Bill date<input name="billDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label>Due date<input name="dueDate" type="date" defaultValue={plusDays(30)} required disabled={disabled} /></label><label className="full">{c.notes}<textarea name="notes" rows={2} disabled={disabled} /></label><div className="full core-preview-list">{payload.map((line) => <div key={line.purchaseOrderItemId}><span>{order?.items.find((item) => item.id === line.purchaseOrderItemId)?.description}</span><strong>{line.quantity} × {money(line.unitCost)}</strong></div>)}</div><PendingActionButton className="primary full" pendingLabel="Posting…" disabled={disabled || !payload.length}>{c.post}</PendingActionButton></form></section>;
}
function ReturnForm({ snapshot, orders, disabled }: { snapshot: PurchasingSnapshot; orders: PurchasingSnapshot["orders"]; disabled: boolean }) {
  const { language } = useLanguage(); const c = coreOperationsCopy[language]; const [orderId, setOrderId] = useState(orders[0]?.id || ""); const order = orders.find((item) => item.id === orderId); const [itemId, setItemId] = useState(""); const item = order?.items.find((line) => line.id === itemId); const bill = snapshot.bills.find((entry) => entry.orderId === orderId); const payload = item ? [{ purchaseOrderItemId: item.id, warehouseId: item.warehouseId, quantity: Math.max(item.receivedQuantity - item.returnedQuantity, 0) }] : [];
  useMemo(() => { if (order && !order.items.some((line) => line.id === itemId)) setItemId(order.items.find((line) => line.receivedQuantity > line.returnedQuantity)?.id || ""); }, [order, itemId]);
  return <section className="core-panel"><p className="eyebrow">Supplier credit</p><h2>Post purchase return</h2><form action={postPurchaseReturnAction} className="core-form"><label className="full">Purchase order<select name="purchaseOrderId" value={orderId} onChange={(event) => setOrderId(event.target.value)} required disabled={disabled}><option value="">Select</option>{orders.map((entry) => <option value={entry.id} key={entry.id}>{entry.number} · {entry.supplierName}</option>)}</select></label><input type="hidden" name="supplierBillId" value={bill?.id || ""} /><label className="full">Item<select value={itemId} onChange={(event) => setItemId(event.target.value)} disabled={disabled}><option value="">Select</option>{order?.items.filter((line) => line.receivedQuantity > line.returnedQuantity).map((line) => <option value={line.id} key={line.id}>{line.description} · {line.receivedQuantity - line.returnedQuantity} available</option>)}</select></label><input type="hidden" name="linesJson" value={JSON.stringify(payload)} /><label>{c.date}<input name="returnDate" type="date" defaultValue={today()} required disabled={disabled} /></label><label className="full">Reason<textarea name="reason" rows={3} required disabled={disabled} /></label><PendingActionButton className="primary full" pendingLabel="Posting…" disabled={disabled || !item || !bill}>{c.post}</PendingActionButton></form></section>;
}