import type { Language } from "./translations";

export const foundationCopies = {
  en: {
    common: {
      dashboard: "Dashboard",
      demoTitle: "Safe demonstration mode",
      demoText: "Sample data only. Configure Supabase and sign in before entering real company information.",
      liveTitle: "Live company data",
      liveText: "Protected by authentication and organization-level database policies.",
      setupGuide: "Setup guide",
      save: "Save",
    },
    customers: {
      title: "Customers",
      description: "Central customer records, credit controls and contact details.",
      created: "Customer created successfully.",
      directory: "Directory",
      count: "customers",
      noContact: "No contact details",
      creditLimit: "Credit limit",
      newLabel: "New customer",
      addTitle: "Add a customer",
      name: "Legal or trading name",
      email: "Email",
      phone: "Phone",
      tin: "TIN",
      creditLimitEtb: "Credit limit (ETB)",
      save: "Save customer",
    },
    inventory: {
      title: "Inventory",
      description: "Products, stock positions, reorder controls and warehouse movements.",
      created: "Product created successfully.",
      stockPosition: "Stock position",
      count: "products",
      available: "Available",
      reorderAt: "Reorder at",
      newLabel: "New product",
      createTitle: "Create product and opening stock",
      sku: "SKU",
      productName: "Product name",
      unitPrice: "Unit price (ETB)",
      costPrice: "Cost price (ETB)",
      openingQuantity: "Opening quantity",
      reorderLevel: "Reorder level",
      save: "Save product",
      warehouseRequired: "Create a warehouse in Supabase before adding products.",
    },
    invoice: {
      title: "New sales invoice",
      description: "One atomic workflow creates the invoice, revenue journal, receivable and stock movement.",
      createdPrefix: "Invoice",
      createdSuffix: "was posted successfully.",
      postedTransaction: "Posted transaction",
      createTitle: "Create invoice",
      explanation: "The database function validates available stock and balanced journal lines before committing.",
      customer: "Customer",
      product: "Product",
      available: "available",
      quantity: "Quantity",
      unitPrice: "Unit price (ETB)",
      taxRate: "VAT rate (%)",
      notes: "Notes",
      post: "Post invoice",
    },
    journals: {
      title: "Journal entries",
      description: "Balanced double-entry postings with immutable history after posting.",
      entry: "Entry",
      date: "Date",
      memo: "Memo",
      status: "Status",
      debit: "Debit",
      credit: "Credit",
    },
    auth: {
      secureWorkspace: "Secure workspace",
      loginTitle: "Sign in to your company",
      loginDescription: "Access live finance, sales, customers and inventory records.",
      supabaseMissing: "Supabase environment variables are not configured. The public dashboard remains in safe demo mode.",
      email: "Email",
      password: "Password",
      signIn: "Sign in",
      newUser: "New to Hisab ERP?",
      createAccount: "Create a company account",
      onboardingLabel: "Company onboarding",
      signupTitle: "Create your secure workspace",
      signupDescription: "The first confirmed user becomes the organization owner.",
      fullName: "Full name",
      organizationName: "Organization name",
      phone: "Phone",
      passwordHelp: "Use at least 10 characters. Enable MFA in Supabase before production launch.",
      create: "Create account",
      existing: "Already registered?",
      complete: "Setup complete",
      openDashboard: "Open dashboard",
      finalStep: "One final step",
      createOrg: "Create your organization",
      orgExplanation: "This establishes the company boundary used by all row-level security policies.",
      tin: "TIN",
      finish: "Finish setup",
    },
    setup: {
      back: "Dashboard",
      label: "Deployment checklist",
      title: "Connect Hisab ERP to Supabase",
      steps: [
        "Create a Supabase project in the same region as most customers.",
        "Run the foundation SQL migration in the Supabase SQL editor.",
        "Add the Supabase URL and publishable key to Vercel.",
        "Set the production application URL and add the authentication callback URL in Supabase.",
        "Create the first account, confirm its email and finish organization onboarding.",
        "Enable MFA, configure backups and test restoration before entering real data.",
      ],
      controlsTitle: "Production controls",
      controlsText: "Row-level security isolates organizations. Posted journals cannot be edited. Sales invoices post through one database transaction. Audit events record sensitive actions. Keep the service-role key server-only.",
      backupsTitle: "Backups",
      backupsText: "Enable point-in-time recovery where available and schedule an encrypted external PostgreSQL backup. Review the backup and recovery document in the repository.",
    },
    errors: {
      routeLabel: "Something went wrong",
      routeTitle: "We could not load this ERP screen.",
      routeText: "Your data was not changed. Try again, or return to the dashboard.",
      tryAgain: "Try again",
      reference: "Reference",
      notFoundLabel: "404",
      notFoundTitle: "This ERP page does not exist.",
      notFoundText: "The module may have moved or is not available for your role.",
      returnDashboard: "Return to dashboard",
      loading: "Loading Hisab ERP…",
    },
  },
  am: {
    common: {
      dashboard: "ዳሽቦርድ",
      demoTitle: "ደህንነቱ የተጠበቀ የማሳያ ሁኔታ",
      demoText: "ይህ የምሳሌ ውሂብ ብቻ ነው። እውነተኛ የድርጅት መረጃ ከማስገባትዎ በፊት Supabase ያዋቅሩና ይግቡ።",
      liveTitle: "እውነተኛ የድርጅት ውሂብ",
      liveText: "በመግቢያ ማረጋገጫና በድርጅት ደረጃ የዳታቤዝ ፖሊሲዎች የተጠበቀ ነው።",
      setupGuide: "የማዋቀር መመሪያ",
      save: "አስቀምጥ",
    },
    customers: {
      title: "ደንበኞች",
      description: "የደንበኞች መዝገብ፣ የብድር ቁጥጥርና የመገናኛ መረጃ።",
      created: "ደንበኛው በተሳካ ሁኔታ ተፈጥሯል።",
      directory: "የደንበኞች ዝርዝር",
      count: "ደንበኞች",
      noContact: "የመገናኛ መረጃ የለም",
      creditLimit: "የብድር ገደብ",
      newLabel: "አዲስ ደንበኛ",
      addTitle: "ደንበኛ ጨምር",
      name: "ሕጋዊ ወይም የንግድ ስም",
      email: "ኢሜይል",
      phone: "ስልክ",
      tin: "ቲን",
      creditLimitEtb: "የብድር ገደብ (ብር)",
      save: "ደንበኛ አስቀምጥ",
    },
    inventory: {
      title: "ክምችት",
      description: "ምርቶች፣ የክምችት መጠን፣ የድጋሚ ትዕዛዝ ቁጥጥርና የመጋዘን እንቅስቃሴዎች።",
      created: "ምርቱ በተሳካ ሁኔታ ተፈጥሯል።",
      stockPosition: "የክምችት ሁኔታ",
      count: "ምርቶች",
      available: "ያለ",
      reorderAt: "ድጋሚ ማዘዣ መጠን",
      newLabel: "አዲስ ምርት",
      createTitle: "ምርትና መነሻ ክምችት ፍጠር",
      sku: "የምርት ኮድ",
      productName: "የምርት ስም",
      unitPrice: "የአንዱ ዋጋ (ብር)",
      costPrice: "የግዢ ዋጋ (ብር)",
      openingQuantity: "መነሻ ብዛት",
      reorderLevel: "የድጋሚ ትዕዛዝ መጠን",
      save: "ምርት አስቀምጥ",
      warehouseRequired: "ምርት ከመጨመርዎ በፊት በSupabase ውስጥ መጋዘን ይፍጠሩ።",
    },
    invoice: {
      title: "አዲስ የሽያጭ ደረሰኝ",
      description: "አንድ የተጠበቀ ሂደት ደረሰኝ፣ የገቢ ጆርናል፣ ተቀባይ ሂሳብና የክምችት እንቅስቃሴ ይፈጥራል።",
      createdPrefix: "ደረሰኝ",
      createdSuffix: "በተሳካ ሁኔታ ተመዝግቧል።",
      postedTransaction: "የተመዘገበ ግብይት",
      createTitle: "ደረሰኝ ፍጠር",
      explanation: "ዳታቤዙ ከማስቀመጡ በፊት ያለውን ክምችትና የተመጣጠኑ የጆርናል መስመሮችን ያረጋግጣል።",
      customer: "ደንበኛ",
      product: "ምርት",
      available: "ያለ",
      quantity: "ብዛት",
      unitPrice: "የአንዱ ዋጋ (ብር)",
      taxRate: "የቫት መጠን (%)",
      notes: "ማስታወሻ",
      post: "ደረሰኝ መዝግብ",
    },
    journals: {
      title: "የጆርናል መዝገቦች",
      description: "ከተመዘገቡ በኋላ የማይቀየሩ የተመጣጠኑ ድርብ የሂሳብ መዝገቦች።",
      entry: "መዝገብ",
      date: "ቀን",
      memo: "መግለጫ",
      status: "ሁኔታ",
      debit: "ዴቢት",
      credit: "ክሬዲት",
    },
    auth: {
      secureWorkspace: "ደህንነቱ የተጠበቀ የሥራ ቦታ",
      loginTitle: "ወደ ድርጅትዎ ይግቡ",
      loginDescription: "እውነተኛ የፋይናንስ፣ ሽያጭ፣ ደንበኛና ክምችት መዝገቦችን ይጠቀሙ።",
      supabaseMissing: "የSupabase አካባቢ ተለዋዋጮች አልተዋቀሩም። የህዝብ ዳሽቦርድ በደህንነት የማሳያ ሁኔታ ይቆያል።",
      email: "ኢሜይል",
      password: "የይለፍ ቃል",
      signIn: "ግባ",
      newUser: "ለHisab ERP አዲስ ነዎት?",
      createAccount: "የድርጅት መለያ ፍጠር",
      onboardingLabel: "የድርጅት ማዋቀር",
      signupTitle: "ደህንነቱ የተጠበቀ የሥራ ቦታዎን ይፍጠሩ",
      signupDescription: "የመጀመሪያው የተረጋገጠ ተጠቃሚ የድርጅቱ ባለቤት ይሆናል።",
      fullName: "ሙሉ ስም",
      organizationName: "የድርጅት ስም",
      phone: "ስልክ",
      passwordHelp: "ቢያንስ 10 ቁምፊዎችን ይጠቀሙ። ወደ ምርት ከመግባት በፊት MFA ያንቁ።",
      create: "መለያ ፍጠር",
      existing: "ቀድሞ ተመዝግበዋል?",
      complete: "ማዋቀር ተጠናቋል",
      openDashboard: "ዳሽቦርድ ክፈት",
      finalStep: "የመጨረሻ እርምጃ",
      createOrg: "ድርጅትዎን ይፍጠሩ",
      orgExplanation: "ይህ በሁሉም የዳታቤዝ ደህንነት ፖሊሲዎች የሚጠቀሙበትን የድርጅት ድንበር ይፈጥራል።",
      tin: "ቲን",
      finish: "ማዋቀር ጨርስ",
    },
    setup: {
      back: "ዳሽቦርድ",
      label: "የማሰማራት ዝርዝር",
      title: "Hisab ERPን ከSupabase ጋር ያገናኙ",
      steps: [
        "አብዛኛዎቹ ደንበኞች በሚገኙበት ክልል የSupabase ፕሮጀክት ይፍጠሩ።",
        "የመሠረት SQL ማይግሬሽኑን በSupabase SQL አርታዒ ውስጥ ያስኪዱ።",
        "የSupabase URLና የህዝብ ቁልፍ ወደ Vercel ያክሉ።",
        "የምርት መተግበሪያ URLን ያስቀምጡና የመግቢያ መመለሻ URLን በSupabase ያክሉ።",
        "የመጀመሪያውን መለያ ይፍጠሩ፣ ኢሜይሉን ያረጋግጡና የድርጅት ማዋቀሩን ይጨርሱ።",
        "እውነተኛ ውሂብ ከማስገባትዎ በፊት MFA ያንቁ፣ ምትኬ ያዋቅሩና መመለስን ይፈትሹ።",
      ],
      controlsTitle: "የምርት ቁጥጥሮች",
      controlsText: "የረድፍ ደህንነት ድርጅቶችን ይለያል። የተመዘገቡ ጆርናሎች አይቀየሩም። የሽያጭ ደረሰኞች በአንድ የዳታቤዝ ግብይት ይመዘገባሉ። የኦዲት ክስተቶች አስፈላጊ እርምጃዎችን ይመዘግባሉ።",
      backupsTitle: "ምትኬ",
      backupsText: "በሚገኝበት ጊዜ የጊዜ ነጥብ መመለሻን ያንቁና የተመሰጠረ የPostgreSQL ውጫዊ ምትኬ ያዘጋጁ።",
    },
    errors: {
      routeLabel: "ችግኝ ተፈጥሯል",
      routeTitle: "ይህን የERP ገጽ መጫን አልቻልንም።",
      routeText: "ውሂብዎ አልተቀየረም። እንደገና ይሞክሩ ወይም ወደ ዳሽቦርድ ይመለሱ።",
      tryAgain: "እንደገና ሞክር",
      reference: "ማጣቀሻ",
      notFoundLabel: "404",
      notFoundTitle: "ይህ የERP ገጽ የለም።",
      notFoundText: "ሞጁሉ ተዛውሮ ሊሆን ይችላል ወይም ለእርስዎ ሚና አይገኝም።",
      returnDashboard: "ወደ ዳሽቦርድ ተመለስ",
      loading: "Hisab ERP በመጫን ላይ…",
    },
  },
  ti: {
    common: {
      dashboard: "ዳሽቦርድ",
      demoTitle: "ውሑስ ናይ መርኣያ ኩነታት",
      demoText: "እዚ ናይ ኣብነት ዳታ ጥራይ እዩ። ናይ ሓቂ ውድብ ሓበሬታ ቅድሚ ምእታውኩም Supabase ኣዋቕሩን እተዉን።",
      liveTitle: "ናይ ሓቂ ውድብ ዳታ",
      liveText: "ብመንነት ምርግጋጽን ብደረጃ ውድብ ፖሊሲታት ዳታቤዝን ዝተሓለወ እዩ።",
      setupGuide: "መምርሒ ምውቓር",
      save: "ዓቅብ",
    },
    customers: {
      title: "ዓማዊል",
      description: "ማእከላይ መዝገብ ዓማዊል፣ ቁጽጽር ልቓሕን ሓበሬታ ርክብን።",
      created: "ዓሚል ብዓወት ተፈጢሩ።",
      directory: "ዝርዝር",
      count: "ዓማዊል",
      noContact: "ሓበሬታ ርክብ የለን",
      creditLimit: "ደረት ልቓሕ",
      newLabel: "ሓድሽ ዓሚል",
      addTitle: "ዓሚል ወስኽ",
      name: "ሕጋዊ ወይ ንግዳዊ ስም",
      email: "ኢመይል",
      phone: "ተሌፎን",
      tin: "ቲን",
      creditLimitEtb: "ደረት ልቓሕ (ብር)",
      save: "ዓሚል ዓቅብ",
    },
    inventory: {
      title: "ስቶክ",
      description: "ፍርያት፣ መጠን ስቶክ፣ ቁጽጽር ዳግማይ ትእዛዝን ምንቅስቓስ መኽዘንን።",
      created: "ፍርያት ብዓወት ተፈጢሩ።",
      stockPosition: "ኩነታት ስቶክ",
      count: "ፍርያት",
      available: "ዘሎ",
      reorderAt: "ዳግማይ ትእዛዝ ኣብ",
      newLabel: "ሓድሽ ፍርያት",
      createTitle: "ፍርያትን መጀመርታ ስቶክን ፍጠር",
      sku: "ኮድ ፍርያት",
      productName: "ስም ፍርያት",
      unitPrice: "ዋጋ ሓደ (ብር)",
      costPrice: "ዋጋ ዕድጊ (ብር)",
      openingQuantity: "መጀመርታ ብዝሒ",
      reorderLevel: "ደረጃ ዳግማይ ትእዛዝ",
      save: "ፍርያት ዓቅብ",
      warehouseRequired: "ፍርያት ቅድሚ ምውሳኽኩም ኣብ Supabase መኽዘን ፍጠሩ።",
    },
    invoice: {
      title: "ሓድሽ ደረሰኝ ሽያጭ",
      description: "ሓደ ውሑስ መስርሕ ደረሰኝ፣ ጆርናል እቶት፣ ተቐባሊ ሕሳብን ምንቅስቓስ ስቶክን ይፈጥር።",
      createdPrefix: "ደረሰኝ",
      createdSuffix: "ብዓወት ተመዝጊቡ።",
      postedTransaction: "ዝተመዝገበ ልውውጥ",
      createTitle: "ደረሰኝ ፍጠር",
      explanation: "ዳታቤዝ ቅድሚ ምዕቃብ ዘሎ ስቶክን ሚዛናዊ መስመራት ጆርናልን የረጋግጽ።",
      customer: "ዓሚል",
      product: "ፍርያት",
      available: "ዘሎ",
      quantity: "ብዝሒ",
      unitPrice: "ዋጋ ሓደ (ብር)",
      taxRate: "መጠን ቫት (%)",
      notes: "መዘኻኸሪ",
      post: "ደረሰኝ መዝግብ",
    },
    journals: {
      title: "መዝገባት ጆርናል",
      description: "ድሕሪ ምምዝጋብ ዘይቅየሩ ሚዛናዊ ድርብ መዝገባት ሕሳብ።",
      entry: "መዝገብ",
      date: "ዕለት",
      memo: "መግለጺ",
      status: "ኩነታት",
      debit: "ዴቢት",
      credit: "ክሬዲት",
    },
    auth: {
      secureWorkspace: "ውሑስ መስርሒ ቦታ",
      loginTitle: "ናብ ውድብኩም እተዉ",
      loginDescription: "ናይ ሓቂ ፋይናንስ፣ ሽያጭ፣ ዓማዊልን ስቶክን መዝገባት ተጠቐሙ።",
      supabaseMissing: "ናይ Supabase ከባቢ ተለዋዋጢታት ኣይተዋቐሩን። ህዝባዊ ዳሽቦርድ ኣብ ውሑስ መርኣያ ኩነታት ይጸንሕ።",
      email: "ኢመይል",
      password: "መሕለፊ ቃል",
      signIn: "እቶ",
      newUser: "ንHisab ERP ሓድሽ ዲኹም?",
      createAccount: "ናይ ውድብ ኣካውንት ፍጠሩ",
      onboardingLabel: "ምውቓር ውድብ",
      signupTitle: "ውሑስ መስርሒ ቦታኹም ፍጠሩ",
      signupDescription: "እቲ ቀዳማይ ዝተረጋገጸ ተጠቃሚ ዋና ውድብ ይኸውን።",
      fullName: "ምሉእ ስም",
      organizationName: "ስም ውድብ",
      phone: "ተሌፎን",
      passwordHelp: "እንተወሓደ 10 ፊደላት ተጠቐሙ። ቅድሚ ምህርቲ MFA ኣንቅሑ።",
      create: "ኣካውንት ፍጠር",
      existing: "ድሮ ተመዝጊብኩም ዲኹም?",
      complete: "ምውቓር ተዛዚሙ",
      openDashboard: "ዳሽቦርድ ክፈት",
      finalStep: "መወዳእታ ስጉምቲ",
      createOrg: "ውድብኩም ፍጠሩ",
      orgExplanation: "እዚ ኣብ ኩሎም ፖሊሲታት ድሕነት ዳታቤዝ ዝጥቀም ዶብ ውድብ ይፈጥር።",
      tin: "ቲን",
      finish: "ምውቓር ዛዝም",
    },
    setup: {
      back: "ዳሽቦርድ",
      label: "ዝርዝር ምዝርጋሕ",
      title: "Hisab ERP ምስ Supabase ኣራኽቡ",
      steps: [
        "ኣብ መብዛሕትኦም ዓማዊል ዝርከቡሉ ዞባ ፕሮጀክት Supabase ፍጠሩ።",
        "ናይ መሰረት SQL migration ኣብ Supabase SQL editor ኣካይዱ።",
        "URL Supabaseን ህዝባዊ መፍትሕን ናብ Vercel ወስኹ።",
        "URL ምህርቲ ኣቐምጡን URL ምምላስ መንነት ኣብ Supabase ወስኹን።",
        "ቀዳማይ ኣካውንት ፍጠሩ፣ ኢመይል ኣረጋግጹን ምውቓር ውድብ ዛዝሙን።",
        "ቅድሚ ናይ ሓቂ ዳታ ምእታው MFA ኣንቅሑ፣ backup ኣዋቕሩን restore ፈትኑን።",
      ],
      controlsTitle: "ቁጽጽራት ምህርቲ",
      controlsText: "Row-level security ውድባት ይፈላልይ። ዝተመዝገቡ ጆርናላት ኣይቅየሩን። ደረሰኛት ሽያጭ ብሓደ ግብይት ዳታቤዝ ይምዝገቡ። ናይ ኦዲት ፍጻመታት ኣገደስቲ ስጉምቲታት ይምዝግቡ።",
      backupsTitle: "ምትኬ",
      backupsText: "ኣብ ዝርከበሉ point-in-time recovery ኣንቅሑን ዝተመስጠረ ውጫዊ PostgreSQL backup ኣዳልዉን።",
    },
    errors: {
      routeLabel: "ጸገም ኣጋጢሙ",
      routeTitle: "እዚ ገጽ ERP ክንጽዕን ኣይከኣልናን።",
      routeText: "ዳታኹም ኣይተቐየረን። እንደገና ፈትኑ ወይ ናብ ዳሽቦርድ ተመለሱ።",
      tryAgain: "እንደገና ፈትን",
      reference: "መወከሲ",
      notFoundLabel: "404",
      notFoundTitle: "እዚ ገጽ ERP የለን።",
      notFoundText: "ሞጁሉ ተዛዊሩ ክኸውን ይኽእል ወይ ንግደኹም ኣይፍቀድን።",
      returnDashboard: "ናብ ዳሽቦርድ ተመለስ",
      loading: "Hisab ERP ይጽዕን ኣሎ…",
    },
  },
} as const satisfies Record<Language, unknown>;

export type FoundationCopy = (typeof foundationCopies)["en"];

export function getFoundationCopy(language: Language): FoundationCopy {
  return foundationCopies[language] as unknown as FoundationCopy;
}
