create table if not exists public.employees (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),employee_number text not null,first_name text not null,last_name text not null,email text,phone text,tax_id text,pension_id text,hire_date date not null,termination_date date,department text,position_title text,employment_type text not null default 'permanent' check(employment_type in ('permanent','contract','temporary','intern')),status text not null default 'active' check(status in ('active','on_leave','suspended','terminated')),bank_name text,bank_account_masked text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,employee_number));
create table if not exists public.attendance_entries (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,attendance_date date not null,status text not null check(status in ('present','absent','late','half_day','remote','holiday','leave')),check_in time,check_out time,regular_hours numeric(6,2) not null default 0,overtime_hours numeric(6,2) not null default 0,notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,employee_id,attendance_date));
create table if not exists public.leave_requests (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,leave_number text not null,leave_type text not null check(leave_type in ('annual','sick','maternity','paternity','unpaid','other')),start_date date not null,end_date date not null,days numeric(7,2) not null check(days>0),status text not null default 'submitted' check(status in ('draft','submitted','approved','rejected','cancelled')),reason text,approver_note text,created_by uuid references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date),unique(organization_id,leave_number));
create table if not exists public.salary_structures (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,effective_from date not null,base_salary numeric(18,2) not null check(base_salary>=0),recurring_allowances numeric(18,2) not null default 0 check(recurring_allowances>=0),recurring_deductions numeric(18,2) not null default 0 check(recurring_deductions>=0),employee_pension_rate numeric(7,4) not null default 0 check(employee_pension_rate between 0 and 100),employer_pension_rate numeric(7,4) not null default 0 check(employer_pension_rate between 0 and 100),income_tax_rate numeric(7,4) not null default 0 check(income_tax_rate between 0 and 100),overtime_hourly_rate numeric(18,2) not null default 0 check(overtime_hourly_rate>=0),is_active boolean not null default true,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(employee_id,effective_from));
create table if not exists public.payroll_runs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),payroll_number text not null,period_start date not null,period_end date not null,pay_date date not null,status text not null default 'draft' check(status in ('draft','approved','posted','paid','cancelled')),gross_pay numeric(18,2) not null default 0,employee_pension numeric(18,2) not null default 0,employer_pension numeric(18,2) not null default 0,income_tax numeric(18,2) not null default 0,other_deductions numeric(18,2) not null default 0,net_pay numeric(18,2) not null default 0,journal_entry_id uuid references public.journal_entries(id),payment_journal_entry_id uuid references public.journal_entries(id),notes text,created_by uuid references auth.users(id),approved_by uuid references auth.users(id),posted_by uuid references auth.users(id),posted_at timestamptz,paid_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(period_end>=period_start),unique(organization_id,payroll_number));
create table if not exists public.payroll_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,payroll_run_id uuid not null references public.payroll_runs(id) on delete cascade,employee_id uuid not null references public.employees(id),base_salary numeric(18,2) not null,allowances numeric(18,2) not null default 0,overtime_pay numeric(18,2) not null default 0,gross_pay numeric(18,2) not null,employee_pension numeric(18,2) not null default 0,employer_pension numeric(18,2) not null default 0,income_tax numeric(18,2) not null default 0,other_deductions numeric(18,2) not null default 0,net_pay numeric(18,2) not null,attendance_days numeric(7,2) not null default 0,leave_days numeric(7,2) not null default 0,created_at timestamptz not null default now(),unique(payroll_run_id,employee_id));

create or replace view public.employee_payroll_view with (security_invoker=true) as select e.id,e.organization_id,e.employee_number,e.first_name||' '||e.last_name full_name,e.department,e.position_title,e.status,ss.base_salary,ss.recurring_allowances,ss.employee_pension_rate,ss.employer_pension_rate,ss.income_tax_rate from public.employees e left join lateral (select * from public.salary_structures s where s.employee_id=e.id and s.is_active order by effective_from desc limit 1) ss on true;

do $$ declare t text; begin foreach t in array array['employees','attendance_entries','leave_requests','salary_structures','payroll_runs','payroll_items'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists org_select on public.%I',t); execute format('create policy org_select on public.%I for select to authenticated using (public.is_org_member(organization_id))',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end $$;
grant select on public.employee_payroll_view to authenticated;

create index if not exists employees_org_idx on public.employees(organization_id,status,department,employee_number);
create index if not exists attendance_org_date_idx on public.attendance_entries(organization_id,attendance_date desc,employee_id);
create index if not exists leave_requests_org_idx on public.leave_requests(organization_id,status,start_date);
create index if not exists salary_structures_employee_idx on public.salary_structures(employee_id,effective_from desc,is_active);
create index if not exists payroll_runs_org_idx on public.payroll_runs(organization_id,status,period_end desc);
create index if not exists payroll_items_run_idx on public.payroll_items(payroll_run_id);