-- Dedicated procure-to-pay and accounts payable records.

create table if not exists public.suppliers (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),name text not null,email text,phone text,tin text,payment_terms_days integer not null default 0 check(payment_terms_days>=0),credit_limit numeric(18,2) not null default 0 check(credit_limit>=0),bank_details text,is_active boolean not null default true,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,name));
create table if not exists public.purchase_requests (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),request_number text not null,request_date date not null default current_date,needed_by date,department text,requested_by_name text,status text not null default 'draft' check(status in ('draft','submitted','approved','rejected','converted','cancelled')),notes text,created_by uuid references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,request_number));
create table if not exists public.purchase_request_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,purchase_request_id uuid not null references public.purchase_requests(id) on delete cascade,product_id uuid references public.products(id),description text not null,quantity numeric(18,3) not null check(quantity>0),estimated_unit_cost numeric(18,2) not null default 0 check(estimated_unit_cost>=0),warehouse_id uuid references public.warehouses(id),created_at timestamptz not null default now());
create table if not exists public.supplier_quotes (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,purchase_request_id uuid references public.purchase_requests(id),supplier_id uuid not null references public.suppliers(id),quote_number text not null,supplier_reference text,quote_date date not null default current_date,valid_until date,status text not null default 'received' check(status in ('received','selected','rejected','expired','converted')),subtotal numeric(18,2) not null default 0,tax_amount numeric(18,2) not null default 0,total numeric(18,2) generated always as (subtotal+tax_amount) stored,notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,quote_number));
create table if not exists public.supplier_quote_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,supplier_quote_id uuid not null references public.supplier_quotes(id) on delete cascade,product_id uuid references public.products(id),warehouse_id uuid references public.warehouses(id),description text not null,quantity numeric(18,3) not null check(quantity>0),unit_cost numeric(18,2) not null check(unit_cost>=0),tax_rate numeric(7,4) not null default 0 check(tax_rate between 0 and 100),line_subtotal numeric(18,2) not null,line_tax numeric(18,2) not null default 0,created_at timestamptz not null default now());
create table if not exists public.purchase_orders (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),supplier_id uuid not null references public.suppliers(id),purchase_request_id uuid references public.purchase_requests(id),supplier_quote_id uuid references public.supplier_quotes(id),order_number text not null,order_date date not null default current_date,expected_date date,status text not null default 'draft' check(status in ('draft','approved','sent','partially_received','received','billed','closed','cancelled')),subtotal numeric(18,2) not null default 0,tax_amount numeric(18,2) not null default 0,total numeric(18,2) generated always as (subtotal+tax_amount) stored,notes text,created_by uuid references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,order_number));
create table if not exists public.purchase_order_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,product_id uuid references public.products(id),warehouse_id uuid references public.warehouses(id),description text not null,quantity numeric(18,3) not null check(quantity>0),received_quantity numeric(18,3) not null default 0 check(received_quantity>=0),billed_quantity numeric(18,3) not null default 0 check(billed_quantity>=0),returned_quantity numeric(18,3) not null default 0 check(returned_quantity>=0),unit_cost numeric(18,2) not null check(unit_cost>=0),tax_rate numeric(7,4) not null default 0 check(tax_rate between 0 and 100),line_subtotal numeric(18,2) not null,line_tax numeric(18,2) not null default 0,created_at timestamptz not null default now());
create table if not exists public.goods_receipts (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),purchase_order_id uuid not null references public.purchase_orders(id),receipt_number text not null,receipt_date date not null default current_date,supplier_delivery_reference text,status text not null default 'posted' check(status in ('draft','posted','cancelled')),notes text,created_by uuid references auth.users(id),posted_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,receipt_number));
create table if not exists public.goods_receipt_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,goods_receipt_id uuid not null references public.goods_receipts(id) on delete cascade,purchase_order_item_id uuid not null references public.purchase_order_items(id),product_id uuid not null references public.products(id),warehouse_id uuid not null references public.warehouses(id),quantity numeric(18,3) not null check(quantity>0),unit_cost numeric(18,2) not null check(unit_cost>=0),lot_number text,expiry_date date,created_at timestamptz not null default now());
create table if not exists public.supplier_bills (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),supplier_id uuid not null references public.suppliers(id),purchase_order_id uuid references public.purchase_orders(id),goods_receipt_id uuid references public.goods_receipts(id),bill_number text not null,supplier_invoice_number text,bill_date date not null default current_date,due_date date not null,status text not null default 'posted' check(status in ('draft','posted','partially_paid','paid','credited','void')),subtotal numeric(18,2) not null default 0,tax_amount numeric(18,2) not null default 0,total numeric(18,2) generated always as (subtotal+tax_amount) stored,paid_amount numeric(18,2) not null default 0,credited_amount numeric(18,2) not null default 0,journal_entry_id uuid references public.journal_entries(id),notes text,created_by uuid references auth.users(id),posted_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,bill_number));
create table if not exists public.supplier_bill_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,supplier_bill_id uuid not null references public.supplier_bills(id) on delete cascade,purchase_order_item_id uuid references public.purchase_order_items(id),product_id uuid references public.products(id),description text not null,quantity numeric(18,3) not null check(quantity>0),unit_cost numeric(18,2) not null check(unit_cost>=0),tax_rate numeric(7,4) not null default 0 check(tax_rate between 0 and 100),line_subtotal numeric(18,2) not null,line_tax numeric(18,2) not null default 0,expense_account_id uuid references public.accounts(id),created_at timestamptz not null default now());
create table if not exists public.supplier_bill_payments (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,supplier_bill_id uuid not null references public.supplier_bills(id) on delete cascade,payment_id uuid not null references public.payments(id),amount numeric(18,2) not null check(amount>0),created_at timestamptz not null default now());
create table if not exists public.purchase_returns (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),supplier_id uuid not null references public.suppliers(id),purchase_order_id uuid references public.purchase_orders(id),supplier_bill_id uuid references public.supplier_bills(id),return_number text not null,return_date date not null default current_date,status text not null default 'posted' check(status in ('draft','posted','cancelled')),subtotal numeric(18,2) not null default 0,tax_amount numeric(18,2) not null default 0,total numeric(18,2) generated always as (subtotal+tax_amount) stored,reason text,journal_entry_id uuid references public.journal_entries(id),created_by uuid references auth.users(id),posted_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,return_number));
create table if not exists public.purchase_return_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,purchase_return_id uuid not null references public.purchase_returns(id) on delete cascade,purchase_order_item_id uuid references public.purchase_order_items(id),product_id uuid not null references public.products(id),warehouse_id uuid not null references public.warehouses(id),quantity numeric(18,3) not null check(quantity>0),unit_cost numeric(18,2) not null check(unit_cost>=0),tax_rate numeric(7,4) not null default 0,line_subtotal numeric(18,2) not null,line_tax numeric(18,2) not null default 0,created_at timestamptz not null default now());

create or replace view public.supplier_balance_view with (security_invoker=true) as select s.id,s.organization_id,s.name,coalesce(sum(b.total-b.credited_amount-b.paid_amount),0)::numeric(18,2) balance,coalesce(sum(b.total),0)::numeric(18,2) billed,coalesce(sum(b.paid_amount),0)::numeric(18,2) paid from public.suppliers s left join public.supplier_bills b on b.supplier_id=s.id and b.status<>'void' group by s.id;
create or replace view public.purchase_order_progress_view with (security_invoker=true) as select po.id,po.organization_id,po.order_number,po.supplier_id,po.status,po.total,coalesce(sum(i.quantity),0) ordered_quantity,coalesce(sum(i.received_quantity),0) received_quantity,coalesce(sum(i.billed_quantity),0) billed_quantity from public.purchase_orders po left join public.purchase_order_items i on i.purchase_order_id=po.id group by po.id;

do $$ declare t text; begin foreach t in array array['suppliers','purchase_requests','purchase_request_items','supplier_quotes','supplier_quote_items','purchase_orders','purchase_order_items','goods_receipts','goods_receipt_items','supplier_bills','supplier_bill_items','supplier_bill_payments','purchase_returns','purchase_return_items'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists org_select on public.%I',t); execute format('create policy org_select on public.%I for select to authenticated using (public.is_org_member(organization_id))',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end $$;
grant select on public.supplier_balance_view,public.purchase_order_progress_view to authenticated;

create index if not exists suppliers_org_idx on public.suppliers(organization_id,is_active,name);
create index if not exists purchase_requests_org_idx on public.purchase_requests(organization_id,status,request_date desc);
create index if not exists purchase_request_items_parent_idx on public.purchase_request_items(purchase_request_id);
create index if not exists supplier_quotes_org_idx on public.supplier_quotes(organization_id,status,quote_date desc);
create index if not exists supplier_quote_items_parent_idx on public.supplier_quote_items(supplier_quote_id);
create index if not exists purchase_orders_org_idx on public.purchase_orders(organization_id,status,order_date desc);
create index if not exists purchase_order_items_parent_idx on public.purchase_order_items(purchase_order_id);
create index if not exists goods_receipts_org_idx on public.goods_receipts(organization_id,receipt_date desc);
create index if not exists goods_receipt_items_parent_idx on public.goods_receipt_items(goods_receipt_id);
create index if not exists supplier_bills_org_idx on public.supplier_bills(organization_id,status,due_date);
create index if not exists supplier_bill_items_parent_idx on public.supplier_bill_items(supplier_bill_id);
create index if not exists supplier_bill_payments_bill_idx on public.supplier_bill_payments(supplier_bill_id);
create index if not exists purchase_returns_org_idx on public.purchase_returns(organization_id,return_date desc);
create index if not exists purchase_return_items_parent_idx on public.purchase_return_items(purchase_return_id);