create table if not exists public.stock_transfers (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),transfer_number text not null,source_warehouse_id uuid not null references public.warehouses(id),destination_warehouse_id uuid not null references public.warehouses(id),transfer_date date not null default current_date,status text not null default 'draft' check(status in ('draft','approved','in_transit','completed','cancelled')),notes text,created_by uuid references auth.users(id),approved_by uuid references auth.users(id),completed_by uuid references auth.users(id),completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(source_warehouse_id<>destination_warehouse_id),unique(organization_id,transfer_number));
create table if not exists public.stock_transfer_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,stock_transfer_id uuid not null references public.stock_transfers(id) on delete cascade,product_id uuid not null references public.products(id),quantity numeric(18,3) not null check(quantity>0),created_at timestamptz not null default now());
create table if not exists public.stock_counts (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),warehouse_id uuid not null references public.warehouses(id),count_number text not null,count_date date not null default current_date,status text not null default 'draft' check(status in ('draft','in_progress','submitted','posted','cancelled')),notes text,created_by uuid references auth.users(id),submitted_by uuid references auth.users(id),posted_by uuid references auth.users(id),posted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,count_number));
create table if not exists public.stock_count_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,stock_count_id uuid not null references public.stock_counts(id) on delete cascade,product_id uuid not null references public.products(id),system_quantity numeric(18,3) not null default 0,counted_quantity numeric(18,3),variance_quantity numeric(18,3) generated always as (coalesce(counted_quantity,system_quantity)-system_quantity) stored,unit_cost numeric(18,2) not null default 0,posted_adjustment_id uuid,created_at timestamptz not null default now(),unique(stock_count_id,product_id));
create table if not exists public.inventory_adjustments (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id),warehouse_id uuid not null references public.warehouses(id),product_id uuid not null references public.products(id),adjustment_number text not null,adjustment_date date not null default current_date,adjustment_type text not null check(adjustment_type in ('increase','decrease')),quantity numeric(18,3) not null check(quantity>0),unit_cost numeric(18,2) not null default 0,reason text not null,source_count_id uuid references public.stock_counts(id),journal_entry_id uuid references public.journal_entries(id),created_by uuid references auth.users(id),posted_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(organization_id,adjustment_number));
create table if not exists public.inventory_lots (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,product_id uuid not null references public.products(id),warehouse_id uuid not null references public.warehouses(id),lot_number text not null,manufacture_date date,expiry_date date,quantity numeric(18,3) not null default 0 check(quantity>=0),status text not null default 'active' check(status in ('active','quarantined','expired','depleted')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,product_id,warehouse_id,lot_number));
create table if not exists public.inventory_serials (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,product_id uuid not null references public.products(id),warehouse_id uuid references public.warehouses(id),serial_number text not null,lot_id uuid references public.inventory_lots(id),status text not null default 'available' check(status in ('available','reserved','sold','returned','damaged','scrapped')),source_type text,source_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,serial_number));

create or replace view public.inventory_reorder_view with (security_invoker=true) as select p.id product_id,p.organization_id,p.sku,p.name,p.reorder_level,coalesce(sum(sb.quantity),0)::numeric(18,3) quantity,case when coalesce(sum(sb.quantity),0)<=p.reorder_level then true else false end needs_reorder from public.products p left join public.stock_balances sb on sb.product_id=p.id group by p.id;

do $$ declare t text; begin foreach t in array array['stock_transfers','stock_transfer_items','stock_counts','stock_count_items','inventory_adjustments','inventory_lots','inventory_serials'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists org_select on public.%I',t); execute format('create policy org_select on public.%I for select to authenticated using (public.is_org_member(organization_id))',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end $$;
grant select on public.inventory_reorder_view to authenticated;

create index if not exists stock_transfers_org_idx on public.stock_transfers(organization_id,status,transfer_date desc);
create index if not exists stock_transfer_items_parent_idx on public.stock_transfer_items(stock_transfer_id);
create index if not exists stock_counts_org_idx on public.stock_counts(organization_id,status,count_date desc);
create index if not exists stock_count_items_parent_idx on public.stock_count_items(stock_count_id);
create index if not exists inventory_adjustments_org_idx on public.inventory_adjustments(organization_id,adjustment_date desc);
create index if not exists inventory_lots_lookup_idx on public.inventory_lots(organization_id,product_id,warehouse_id,status,expiry_date);
create index if not exists inventory_serials_lookup_idx on public.inventory_serials(organization_id,product_id,status);